{
 "title": "Executive dashboards / Single Virtual Machine View",
 "description": "This dashboard provides detailed insights into a specific virtual machine, including its configuration, resource consumption, and any active alerts. It allows users to easily locate the virtual machine across multiple clusters, facilitating efficient monitoring and troubleshooting.",
 "tags": [
  "ACM",
  "KubeVirt",
  "OpenShift",
  "Virtualization"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kubevirt_vm_running_status_last_transition_timestamp_seconds, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "name",
    "label": "VM Name",
    "query": {
     "query": "query_result(sum by (name)(kubevirt_vm_cpu_usage_seconds_total or kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=\"$cluster\", namespace=\"$namespace\"}))"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VM Information",
   "type": "table",
   "gridPos": { "h": 12, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(sum by (name)(kubevirt_vm_cpu_usage_seconds_total or kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=\"$cluster\", namespace=\"$namespace\",name=\"$name\"}), \"Field\", \"Name\", \"name\", \".*\")"
    },
    {
     "expr": "label_replace(sum by (status)(label_replace(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=\"$cluster\",namespace=\"$namespace\",name=\"$name\"}>0,\"status\", \"Running\", \"\", \"\") or label_replace(kubevirt_vm_non_running_status_last_transition_timestamp_seconds{cluster=\"$cluster\",namespace=\"$namespace\",name=\"$name\"}>0,\"status\", \"Stopped\", \"\", \"\") or label_replace(kubevirt_vm_error_status_last_transition_timestamp_seconds{cluster=\"$cluster\",namespace=\"$namespace\",name=\"$name\"}>0,\"status\", \"Error\", \"\", \"\") or label_replace(kubevirt_vm_starting_status_last_transition_timestamp_seconds{cluster=\"$cluster\",namespace=\"$namespace\",name=\"$name\"}>0,\"status\", \"Starting\", \"\", \"\") or label_replace(kubevirt_vm_migrating_status_last_transition_timestamp_seconds{cluster=\"$cluster\",namespace=\"$namespace\",name=\"$name\"}>0,\"status\", \"Migrating\", \"\", \"\") ), \"Field\", \"Status\", \"name\", \".*\")"
    },
    {
     "expr": "label_replace(sum by (guest_os_name)(kubevirt_vm_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\", guest_os_name!=\"\"} or kubevirt_vmi_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\", guest_os_name!=\"\"}), \"Field\", \"Operating System\", \"name\", \".*\")"
    },
    {
     "expr": "label_replace(sum by (guest_os_version_id)(kubevirt_vm_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\", guest_os_version_id!=\"\"} or kubevirt_vmi_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\", guest_os_version_id!=\"\"}), \"Field\", \"Operating System Version\", \"name\", \".*\")"
    },
    {
     "expr": "label_replace(\n  sum by (name) (sum(kubevirt_vm_resource_requests{cluster=\"$cluster\", name=\"$name\", namespace=\"$namespace\", resource=\"cpu\", unit=\"cores\"}) \n    * on (cluster, namespace, vmi) group_left() \n    sum(kubevirt_vm_resource_requests{cluster=\"$cluster\", name=\"$name\", namespace=\"$namespace\", resource=\"cpu\", unit=\"sockets\"}) \n    * on (cluster, namespace, vmi) group_left() \n    sum(kubevirt_vm_resource_requests{cluster=\"$cluster\", name=\"$name\", namespace=\"$namespace\", resource=\"cpu\", unit=\"threads\"})\n  ), \"Field\", \"Allocated CPU\", \"name\", \".*\")"
    },
    {
     "expr": "label_replace(sum by (name)(kubevirt_vm_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\", resource=\"memory\"}) / (1024^3), \"Field\", \"Allocated Memory (GB)\", \"name\", \".*\")"
    },
    {
     "expr": "label_replace(sum by (name)(kubevirt_vm_disk_allocated_size_bytes{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\"})/ (1024^3), \"Field\", \"Allocated Disk (GB)\", \"name\", \".*\")"
    },
    {
     "expr": "label_replace(sum by (instance_type)(kubevirt_vm_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\", instance_type!=\"<none>\"} or kubevirt_vmi_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\", instance_type!=\"<none>\"}), \"Field\", \"Instance Type\", \"name\", \".*\")"
    },
    {
     "expr": "label_replace(sum by (workload)(kubevirt_vm_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\", workload!=\"<none>\"}) or sum by (workload)(kubevirt_vmi_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\", workload!=\"<none>\"}), \"Field\", \"Template Workload\", \"name\", \".*\")"
    },
    {
     "expr": "label_replace(sum by (flavor)(kubevirt_vm_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\", flavor!=\"<none>\"}) or sum by (flavor)(kubevirt_vm_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\", flavor!=\"<none>\"}), \"Field\", \"Template Flavor\", \"name\", \".*\")"
    }
   ]
  },
  {
   "title": "General Information",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(sum by (namespace)(kubevirt_vm_cpu_usage_seconds_total or kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=\"$cluster\", namespace=\"$namespace\",name=\"$name\"}), \"Field\", \"Namespace\", \"name\", \".*\")"
    },
    {
     "expr": "label_replace(sum by (node)(kubevirt_vmi_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\"}), \"Field\", \"Node\", \"name\", \".*\")"
    },
    {
     "expr": "label_replace(sum by(pod)(kubevirt_vmi_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\"}), \"Field\", \"Pod\", \"name\", \".*\")"
    },
    {
     "expr": "label_replace(sum by (evictable)(kubevirt_vmi_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\"}), \"Field\", \"Evictable\", \"name\", \".*\")"
    },
    {
     "expr": "label_replace(sum by (machine_type)(kubevirt_vm_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\", machine_type!=\"\"}) or sum by (workload)(kubevirt_vmi_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\", machine_type!=\"\"}), \"Field\", \"Machine Type\", \"name\", \".*\")"
    },
    {
     "expr": "label_replace(sum by (outdated)(kubevirt_vmi_info{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\"}), \"Field\", \"Outdated\", \"name\", \".*\")"
    }
   ]
  },
  {
   "title": "Critical Severity Alerts",
   "type": "stat",
   "description": "Total number of alerts that are firing with the severity level: critical.",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (cluster,alertname,alertstate,severity,namespace,name,operator_health_impact )(ALERTS{cluster=~\"$cluster\",kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\", pod=~\"virt-launcher-$name.*\", severity=\"critical\"})) or vector(0)"
    }
   ]
  },
  {
   "title": "Warning Severity Alerts",
   "type": "stat",
   "description": "Total number of alerts that are firing with the severity level: warning.",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (cluster,alertname,alertstate,severity,namespace,name,operator_health_impact )(ALERTS{cluster=~\"$cluster\",kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\", pod=~\"virt-launcher-$name.*\", severity=\"warning\"}))  or vector(0)"
    }
   ]
  },
  {
   "title": "Info Severity Alerts",
   "type": "stat",
   "description": "Total number of alerts that are firing with the severity level: warning.",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum by (cluster,alertname,alertstate,severity,namespace,name,operator_health_impact )(ALERTS{cluster=~\"$cluster\",kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\", pod=~\"virt-launcher-$name.*\", severity=\"info\"})) or vector(0)"
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum by (name) (\nkubevirt_vmi_memory_available_bytes{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"} - kubevirt_vmi_memory_unused_bytes{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"} -kubevirt_vmi_memory_cached_bytes{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"}))\n/\n(sum by (name)(kubevirt_vm_resource_requests{cluster=\"$cluster\", namespace=\"$namespace\", name=\"$name\", resource=\"memory\"}))"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (rate(kubevirt_vmi_cpu_usage_seconds_total{cluster=~\"$cluster\", namespace=\"$namespace\", name=\"$name\"}[10m]))\n/\nsum by (name) (\n  sum(kubevirt_vm_resource_requests{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", resource=\"cpu\", unit=\"cores\"})\n  * on (cluster, namespace, vmi) group_left()\n  sum(kubevirt_vm_resource_requests{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", resource=\"cpu\", unit=\"sockets\"})\n  * on (cluster, namespace, vmi) group_left()\n  sum(kubevirt_vm_resource_requests{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", resource=\"cpu\", unit=\"threads\"})\n)"
    }
   ]
  },
  {
   "title": "CPU Delay (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name, namespace, cluster)(rate(kubevirt_vmi_vcpu_delay_seconds_total{cluster=~\"$cluster\", namespace=\"$namespace\", name=\"$name\"}[10m]))\n/ (\n  avg by (cluster, namespace, name)(kubevirt_vm_resource_requests{cluster=~\"$cluster\", namespace=\"$namespace\", name=\"$name\", resource=\"cpu\", unit=\"cores\"})\n  * on (cluster, namespace, name) group_left()\n  avg by (cluster, namespace, name)(kubevirt_vm_resource_requests{cluster=~\"$cluster\", namespace=\"$namespace\", name=\"$name\", resource=\"cpu\", unit=\"sockets\"})\n  * on (cluster, namespace, name) group_left()\n  avg by (cluster, namespace, name)(kubevirt_vm_resource_requests{cluster=~\"$cluster\", namespace=\"$namespace\", name=\"$name\", resource=\"cpu\", unit=\"threads\"})\n)\n"
    }
   ]
  },
  {
   "title": "Additional Virtual Machines Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum by(cluster,name,namespace,address,network_name, type)(kubevirt_vmi_status_addresses{cluster=\"$cluster\",namespace=\"$namespace\",name=\"$name\"})"
      }
     ]
    },
    {
     "title": "VM Snapshots",
     "type": "table",
     "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
     "targets": [
      {
       "expr": "kubevirt_vmsnapshot_succeeded_timestamp_seconds{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"}*1000"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total CPU Usage",
     "type": "timeseries",
     "description": "This panel displays the total VM CPU Usage. CPU Usage represents the rate of CPU time consumed by each VM, providing insight into the most resource-intensive workloads in the cluster during the recent period.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (name) (rate(kubevirt_vmi_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"}[10m]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "CPU Usage (%)",
     "type": "timeseries",
     "description": "This panel displays the VM CPU Usage Percentage. CPU Usage Percentage measures how much of the allocated CPU resources (cores, sockets, and threads) each VM is actively utilizing. It helps identify VMs with high or low CPU utilization relative to their allocated capacity.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (cluster, namespace, name) (rate(kubevirt_vmi_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=\"$namespace\", name=\"$name\"}[10m])) /\n(\n  avg by (cluster, namespace, name)(kubevirt_vm_resource_requests{cluster=\"$cluster\",namespace=\"$namespace\", name=\"$name\", resource=\"cpu\", unit=\"cores\"})\n  * on (cluster, namespace, name) group_left()\n  avg by (cluster, namespace, name)(kubevirt_vm_resource_requests{cluster=\"$cluster\",namespace=\"$namespace\", name=\"$name\", resource=\"cpu\", unit=\"sockets\"})\n  * on (cluster, namespace, name) group_left()\n  avg by (cluster, namespace, name)(kubevirt_vm_resource_requests{cluster=\"$cluster\",namespace=\"$namespace\", name=\"$name\", resource=\"cpu\", unit=\"threads\"})\n)",
       "legendFormat": "{{name}} "
      }
     ]
    },
    {
     "title": "CPU Ready Time",
     "type": "timeseries",
     "description": "This panel shows the VM CPU Ready Time. CPU Ready indicates the proportion of time a VM's virtual CPUs were ready to execute but had to wait for physical CPU resources due to contention.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "100 * sum by (name, namespace, cluster)(rate(kubevirt_vmi_vcpu_delay_seconds_total{cluster=~\"$cluster\", namespace=\"$namespace\", name=\"$name\"}[10m]))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "CPU Delay (%)",
     "type": "timeseries",
     "description": "This panel shows the VM CPU Delay Percentage. CPU Delay indicates the proportion of time a VM's virtual CPUs were ready to execute but had to wait for physical CPU resources due to contention.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by (name, namespace, cluster)(rate(kubevirt_vmi_vcpu_delay_seconds_total{cluster=~\"$cluster\", namespace=\"$namespace\", name=\"$name\"}[10m]))\n/\n(\n  avg by (cluster, namespace, name)(kubevirt_vm_resource_requests{cluster=~\"$cluster\", namespace=\"$namespace\", name=\"$name\", resource=\"cpu\", unit=\"cores\"})\n  * on (cluster, namespace, name) group_left()\n  avg by (cluster, namespace, name)(kubevirt_vm_resource_requests{cluster=~\"$cluster\", namespace=\"$namespace\", name=\"$name\", resource=\"cpu\", unit=\"sockets\"})\n  * on (cluster, namespace, name) group_left()\n  avg by (cluster, namespace, name)(kubevirt_vm_resource_requests{cluster=~\"$cluster\", namespace=\"$namespace\", name=\"$name\", resource=\"cpu\", unit=\"threads\"})\n)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "description": "This panel displays the VM memory usage. The memory usage is calculated as the allocated memory minus unused and cached memory. The data is based on the most recent metrics collected.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (name) (\nkubevirt_vmi_memory_available_bytes{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"} - kubevirt_vmi_memory_unused_bytes{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"} -kubevirt_vmi_memory_cached_bytes{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"})",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Memory Usage (%)",
     "type": "timeseries",
     "description": "This panel displays the VM memory usage Percentage. The memory usage is calculated as the allocated memory minus unused and cached memory. The data is based on the most recent metrics collected.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(sum by (name) (\nkubevirt_vmi_memory_available_bytes{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"} - kubevirt_vmi_memory_unused_bytes{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"} -kubevirt_vmi_memory_cached_bytes{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"}))/\n(sum by (name)(kubevirt_vm_resource_requests{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\",resource=\"memory\"}))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Usage  - Transmit",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(kubevirt_vmi_network_transmit_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"}[1h])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Network Usage - Receive",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sum(rate(kubevirt_vmi_network_receive_bytes_total{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"}[1h])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Network Usage  - Transmit Packets Dropped",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(kubevirt_vmi_network_transmit_packets_dropped_total{cluster=\"$cluster\",namespace=\"$namespace\", name=\"$name\"}[1h])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Network Usage  - Receive Packets Dropped",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(kubevirt_vmi_network_receive_packets_dropped_total{cluster=\"$cluster\",namespace=\"$namespace\", name=\"$name\"}[1h])) by (name)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage IOPs",
     "type": "timeseries",
     "description": "This panel displays the VM storage IOPS (read + write) over the past 10 minutes. The metric aggregates the total input/output operations per second, helping identify workloads with the highest storage activity and potential hotspots for performance optimization.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "sum by (name) (rate(kubevirt_vmi_storage_iops_read_total{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"}[1h]) + rate(kubevirt_vmi_storage_iops_write_total{cluster=~\"$cluster\",namespace=\"$namespace\", name=\"$name\"}[1h]))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "VM Alerts",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "sum by (cluster,alertname,alertstate,severity,namespace,name,operator_health_impact )(ALERTS{cluster=~\"$cluster\",kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\", pod=~\"virt-launcher-$name.*\"})"
      }
     ]
    }
   ]
  }
 ]
}