{
 "title": "Executive dashboards / Single Cluster View",
 "description": "This dashboard provides comprehensive insights into the cluster with OpenShift Virtualization installed. It offers detailed information about the virtual machines (VMs), associated resources, and any active alerts, enabling efficient monitoring and management of virtualization within the cluster.",
 "tags": [
  "Virtualization",
  "KubeVirt",
  "ACM",
  "OpenShift"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kubevirt_hyperconverged_operator_health_status{name=~\".*hyperconverged.*\"},cluster)"
    }
   },
   {
    "name": "health_impact",
    "label": "Alerts - Impact on Operator Health",
    "query": {
     "query": "label_values(ALERTS{kubernetes_operator_part_of=\"kubevirt\"}, operator_health_impact)"
    }
   },
   {
    "name": "severity",
    "label": "Alerts - Severity",
    "query": {
     "query": "label_values(ALERTS{kubernetes_operator_part_of=\"kubevirt\"}, severity)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubevirt_hyperconverged_operator_health_status{name=~\".*hyperconverged.*\", cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Openshift Virt Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csv_succeeded{name=~\".*hyperconverged.*\", cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "description": "Total node count in OpenShift Virtualization clusters",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (cluster) (count(kube_node_status_allocatable{resource=~\".*kubevirt.*\", cluster=~\"$cluster\"}) by (cluster,node)))"
    }
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(kubevirt_vm_error_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}) by (name))"
    }
   ]
  },
  {
   "title": "Virtual Machines by Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0) by (name)) or vector(0)",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(count(kubevirt_vm_non_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0) by (name)) or vector(0)",
     "legendFormat": "Stopped"
    },
    {
     "expr": "sum(count(kubevirt_vm_error_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0) by (name)) or vector(0)",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(count(kubevirt_vm_starting_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0) by (name)) or vector(0)",
     "legendFormat": "Starting"
    },
    {
     "expr": "sum(count(kubevirt_vm_migrating_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0) by (name)) or vector(0)",
     "legendFormat": "Migrating"
    }
   ]
  },
  {
   "title": "Provider",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(acm_managed_cluster_labels{name=~\"$cluster\"}) by (cloud)"
    }
   ]
  },
  {
   "title": "Openshift Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(acm_managed_cluster_labels{name=~\"$cluster\"}) by (openshiftVersion)"
    }
   ]
  },
  {
   "title": "Operator Status",
   "type": "stat",
   "description": "Inspect the Operator Conditions and the Alerts tab for additional details",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster)(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Operator Conditions",
   "type": "stat",
   "description": "Status of HCO conditions - Check the HCO Conditions in the cluster",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster) (kubevirt_hco_system_health_status{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Running VMs by OS",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (os)(sum by (cluster, os)(label_replace(kubevirt_vmi_info{cluster=~\"$cluster\", guest_os_name!=\"\", phase=\"running\"}, \"os\", \"$1\", \"guest_os_name\", \"(.*)\")\n+ on (cluster, namespace, name) group_left()(0*(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0))))"
    },
    {
     "expr": "sum by (os)(sum by (cluster, os)(label_replace(kubevirt_vmi_info{cluster=~\"$cluster\", guest_os_name=\"\", phase=\"running\"}, \"os\", \"unknown\", \"guest_os_name\", \"\")\n+ on (cluster, namespace, name) group_left()(0*(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0))))"
    }
   ]
  },
  {
   "title": "Recent VMs Started",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "bottomk(5, sum by (name, namespace) (sort(time() - (kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0)) / 1 ))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Additional Virtual Machines Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "VMs Running by Node",
     "type": "timeseries",
     "description": "Top 20 nodes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sum(kubevirt_vmi_phase_count{cluster=~\"$cluster\",namespace=~\".*\", phase=~\"running\"}) by (cluster,phase,node))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "VMs by Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(count(kubevirt_vm_starting_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
       "legendFormat": "starting"
      },
      {
       "expr": "sum(count(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
       "legendFormat": "running"
      },
      {
       "expr": "sum(count(kubevirt_vm_migrating_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
       "legendFormat": "migrating"
      },
      {
       "expr": "sum(count(kubevirt_vm_error_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
       "legendFormat": "error"
      },
      {
       "expr": "sum(count(kubevirt_vm_non_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
       "legendFormat": "stopped"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization - Top 20",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes by CPU Utilization",
     "type": "timeseries",
     "description": "This panel displays the CPU Utilization Percentage for the top 20 nodes in the cluster, that are running virtual machines, over the past 1 minute. Node CPU Utilization reflects the rate of CPU usage relative to the node's total capacity, providing insight into the most resource-intensive nodes.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(20,sum(label_replace(instance:node_cpu_utilisation:rate1m{cluster=~\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node, cluster)\n+ on(node, cluster) group_left()\n0*sum(kubevirt_vmi_cpu_usage_seconds_total{cluster=~\"$cluster\"}) by (node, cluster))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "VMs by Total CPU Usage",
     "type": "timeseries",
     "description": "This panel displays the total CPU Usage for the top 20 VMs over the past 10 minutes. CPU Usage represents the rate of CPU time consumed by each VM, providing insight into the most resource-intensive workloads in the cluster during the recent period.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(20,sum by (name) (rate(kubevirt_vmi_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\"}[10m])))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Nodes by CPU Usage (%)",
     "type": "timeseries",
     "description": "This panel shows the CPU Usage Percentage for the top 20 nodes in the cluster, that are running virtual machines, over the past 10 minutes. CPU Usage Percentage is calculated as the proportion of active CPU time (user, system, I/O wait) relative to the total available CPU time. It helps identify nodes with the highest workload demand and potential resource contention.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(20, (sum by (node, cluster)(label_replace(rate(node_cpu_seconds_total{cluster=\"$cluster\", mode!=\"idle\"}[10m]), \"node\", \"$1\", \"instance\", \"(.*)\")) \n  / \n  sum by (node, cluster)(label_replace(rate(node_cpu_seconds_total{cluster=\"$cluster\"}[10m]), \"node\", \"$1\", \"instance\", \"(.*)\"))\n+ on(node, cluster) group_left()\n0*sum by (node, cluster)(kubevirt_vmi_cpu_usage_seconds_total{cluster=~\"$cluster\"}))\n)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "VMs by CPU Usage (%)",
     "type": "timeseries",
     "description": "This panel displays the CPU Usage Percentage for the top 20 VMs over the past 10 minutes. CPU Usage Percentage measures how much of the allocated CPU resources (cores, sockets, and threads) each VM is actively utilizing. It helps identify VMs with high or low CPU utilization relative to their allocated capacity.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(20, sum by (cluster, name, namespace) (\n  rate(kubevirt_vmi_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=~\".*\"}[10m])\n) / (\n  sum by (cluster, namespace, name)(\n    kubevirt_vm_resource_requests{cluster=\"$cluster\", namespace=~\".*\", resource=\"cpu\", unit=\"cores\"}\n  )\n  * on (cluster, namespace, name) group_left()\n  sum by (cluster, namespace, name)(\n    kubevirt_vm_resource_requests{cluster=\"$cluster\", namespace=~\".*\", resource=\"cpu\", unit=\"sockets\"}\n  )\n  * on (cluster, namespace, name) group_left()\n  sum by (cluster, namespace, name)(\n    kubevirt_vm_resource_requests{cluster=\"$cluster\", namespace=~\".*\", resource=\"cpu\", unit=\"threads\"}\n  )\n))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Nodes by CPU Steal time (%)",
     "type": "timeseries",
     "description": "This panel shows the CPU steal time percentage over time for the top 20 nodes in the cluster, that are running virtual machines, over the past 10 minutes.\nIt can indicate resource contention on virtualized nodes. High values suggest VMs are competing for CPU resources, potentially impacting performance.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(20, (sum by (node, cluster)(label_replace(rate(node_cpu_seconds_total{cluster=\"$cluster\", mode=\"steal\"}[10m]), \"node\", \"$1\", \"instance\", \"(.*)\")) \n  / \n  sum by (node, cluster)(label_replace(rate(node_cpu_seconds_total{cluster=\"$cluster\"}[10m]), \"node\", \"$1\", \"instance\", \"(.*)\"))\n+ on(node, cluster) group_left()\n0*sum by (node, cluster)(kubevirt_vmi_cpu_usage_seconds_total{cluster=~\"$cluster\"}))\n)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "VMs by CPU Ready (%)",
     "type": "timeseries",
     "description": "This panel shows the CPU Ready Percentage for the top 20 VMs over the past 10 minutes. CPU Ready indicates the proportion of time a VM's virtual CPUs were ready to execute but had to wait for physical CPU resources due to contention.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(20, sum by (name, namespace, cluster) (\n  sum by (name, namespace, cluster)(rate(kubevirt_vmi_vcpu_delay_seconds_total{cluster=\"$cluster\", namespace=~\".*\"}[10m]))\n  /\n  (\n    avg by (cluster, namespace, name)(kubevirt_vm_resource_requests{cluster=\"$cluster\", namespace=~\".*\", resource=\"cpu\", unit=\"cores\"})\n    * on (cluster, namespace, name) group_left()\n    avg by (cluster, namespace, name)(kubevirt_vm_resource_requests{cluster=\"$cluster\", namespace=~\".*\", resource=\"cpu\", unit=\"sockets\"})\n    * on (cluster, namespace, name) group_left()\n    avg by (cluster, namespace, name)(kubevirt_vm_resource_requests{cluster=\"$cluster\", namespace=~\".*\", resource=\"cpu\", unit=\"threads\"}))\n  )\n)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization - Top 20",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes by Memory Usage",
     "type": "timeseries",
     "description": "This panel shows the Memory Usage for the top 20 nodes in the cluster that are running virtual machines. Memory usage is calculated as the proportion of memory utilized relative to the total available memory on each node. This helps identify resource-intensive nodes hosting virtual machines, enabling proactive resource management.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20,sum(label_replace(instance:node_memory_utilisation:ratio{cluster=~\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node, cluster)\n* sum by (node, cluster)(label_replace(node_memory_MemTotal_bytes{cluster=~\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\"))\n+ on(node, cluster) group_left()\n0*sum(kubevirt_vmi_memory_used_bytes{cluster=~\"$cluster\"}) by (node, cluster)\n)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "VMs by Memory Usage",
     "type": "timeseries",
     "description": "This panel displays the memory usage for the top 20 virtual machines (VMs) in the cluster. Memory usage is calculated as the allocated memory minus unused and cached memory. This provides insight into the most memory-intensive VMs, helping identify resource-heavy workloads and potential optimizations. The data is based on the most recent metrics collected.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20,(sum by (name) (\nkubevirt_vmi_memory_available_bytes{cluster=~\"$cluster\",namespace=~\".*\"} - kubevirt_vmi_memory_unused_bytes{cluster=~\"$cluster\",namespace=~\".*\"} -kubevirt_vmi_memory_cached_bytes{cluster=~\"$cluster\",namespace=~\".*\"})))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Nodes by Memory Usage (%)",
     "type": "timeseries",
     "description": "This panel shows the Memory Usage Percentage for the top 20 nodes in the cluster that are running virtual machines. Memory usage is calculated as the proportion of memory utilized relative to the total available memory on each node. This helps identify resource-intensive nodes hosting virtual machines, enabling proactive resource management.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(20,(\n  sum(label_replace(instance:node_memory_utilisation:ratio{cluster=~\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node, cluster)\n+ on(node, cluster) group_left()\n0*sum(kubevirt_vmi_memory_used_bytes{cluster=~\"$cluster\"}) by (node, cluster)\n )\n)",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "VMs by Memory Usage (%)",
     "type": "timeseries",
     "description": "This panel displays the memory usage for the top 20 virtual machines (VMs) in the cluster. Memory usage is calculated as the allocated memory minus unused and cached memory. This provides insight into the most memory-intensive VMs, helping identify resource-heavy workloads and potential optimizations. The data is based on the most recent metrics collected.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(20,(\n  sum by (name) (\n    kubevirt_vmi_memory_available_bytes{cluster=~\"$cluster\",namespace=~\".*\"} -        \n    kubevirt_vmi_memory_unused_bytes{cluster=~\"$cluster\",namespace=~\".*\"} - \n    kubevirt_vmi_memory_cached_bytes{cluster=~\"$cluster\",namespace=~\".*\"}\n  )\n  /\n  (sum by (name)(kubevirt_vm_resource_requests{cluster=~\"$cluster\",namespace=~\".*\",resource=\"memory\"}))\n )\n)",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Utilization - Top 20",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes by Network Received Bytes",
     "type": "timeseries",
     "description": "This panel displays the top 20 nodes running virtual machines (VMs) based on their total network received bytes over the past hour. It includes only nodes hosting VMs and excludes traffic from the loopback interface. This provides insight into the nodes with the highest incoming network traffic, helping identify workloads with significant data reception requirements.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(20,sum(label_replace(instance:node_network_receive_bytes_excluding_lo:rate1m{cluster=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node, cluster)\n+ on(node, cluster) group_left()\n0*sum(kubevirt_vmi_network_receive_packets_total{cluster=\"$cluster\"}) by (node, cluster))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "VMs by Network Received Bytes",
     "type": "timeseries",
     "description": "This panel displays the top 20 virtual machines (VMs) in the cluster by network received bytes per second over the past 10 minutes. The query measures the rate of incoming network traffic, helping identify VMs with the highest network activity. Use this information to monitor and optimize resource usage for workloads with significant data reception.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(20,sum(rate(kubevirt_vmi_network_receive_bytes_total{cluster=~\"$cluster\"}[10m])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Nodes by Network Transmitted Bytes",
     "type": "timeseries",
     "description": "This panel displays the top 20 nodes running virtual machines (VMs) based on their total network transmitted bytes over the past hour. It includes only nodes hosting VMs and excludes traffic from the loopback interface. This provides insight into the nodes with the highest incoming network traffic, helping identify workloads with significant data reception requirements.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(20,sum(label_replace(instance:node_network_transmit_bytes_excluding_lo:rate1m{cluster=\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\")) by (node, cluster)\n+ on(node, cluster) group_left()\n0*sum(kubevirt_vmi_network_transmit_packets_total{cluster=\"$cluster\"}) by (node, cluster))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "VMs by Network Transmitted Bytes",
     "type": "timeseries",
     "description": "This panel displays the top 20 virtual machines (VMs) in the cluster by network transmitted bytes per second over the past 10 minutes. The query measures the rate of incoming network traffic, helping identify VMs with the highest network activity. Use this information to monitor and optimize resource usage for workloads with significant data reception.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "topk(20,sum(rate(kubevirt_vmi_network_transmit_bytes_total{cluster=~\"$cluster\"}[1h])) by (name))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Utilization - Top 20",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Nodes by VM Storage IOPS",
     "type": "timeseries",
     "description": "This panel displays the top 20 nodes running virtual machines (VMs) based on their combined storage IOPS (read + write) over the past 10 minutes. The metric aggregates the total input/output operations per second for all VMs on each node, helping identify nodes with the highest storage activity and potential bottlenecks.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk(20,sum by (node) (rate(kubevirt_vmi_storage_iops_read_total{cluster=~\"$cluster\"}[10m]) + rate(kubevirt_vmi_storage_iops_write_total{cluster=~\"$cluster\"}[10m])))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "VMs by Storage IOPS",
     "type": "timeseries",
     "description": "This panel displays the top 20 virtual machines (VMs) based on their combined storage IOPS (read + write) over the past 10 minutes. The metric aggregates the total input/output operations per second for each VM, helping identify workloads with the highest storage activity and potential hotspots for performance optimization.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk(20,sum by (name) (rate(kubevirt_vmi_storage_iops_read_total{cluster=~\"$cluster\"}[10m]) + rate(kubevirt_vmi_storage_iops_write_total{cluster=~\"$cluster\"}[10m])))",
       "legendFormat": "{{name}}"
      }
     ]
    },
    {
     "title": "Nodes by VM Storage Traffic",
     "type": "timeseries",
     "description": "This panel displays the top 20 nodes running virtual machines (VMs) based on their combined storage traffic (read + write) over the past 10 minutes. The metric aggregates the total input/output operations for all VMs on each node, helping identify nodes with the highest storage activity and potential bottlenecks.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20,sum by (node) (rate(kubevirt_vmi_storage_read_traffic_bytes_total{cluster=~\"$cluster\"}[10m]) + rate(kubevirt_vmi_storage_write_traffic_bytes_total{cluster=~\"$cluster\"}[10m])))",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "VMs by Storage Traffic",
     "type": "timeseries",
     "description": "This panel displays the top 20 virtual machines (VMs) based on their combined storage traffic (read + write) over the past 10 minutes. The metric aggregates the total input/output operations for the last 10 minutes for each VM, helping identify workloads with the highest storage activity and potential hotspots for performance optimization.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20,sum by (name) (rate(kubevirt_vmi_storage_read_traffic_bytes_total{cluster=~\"$cluster\"}[10m]) + rate(kubevirt_vmi_storage_write_traffic_bytes_total{cluster=~\"$cluster\"}[10m])))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Critical Severity Alerts",
     "type": "stat",
     "description": "Total number of alerts that are firing with the severity level: critical.",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (ALERTS{kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\",cluster=~\"$cluster\",severity=\"critical\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Warning Severity Alerts",
     "type": "stat",
     "description": "Total number of alerts that are firing with the severity level: warning.",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (ALERTS{kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\",cluster=~\"$cluster\",severity=\"warning\",operator_health_impact=~\"$health_impact\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Info Severity Alerts",
     "type": "stat",
     "description": "Total number of alerts that are firing with the severity level: warning.",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 20 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum (ALERTS{kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\",cluster=~\"$cluster\",severity=\"info\"}) or vector(0)"
      }
     ]
    },
    {
     "title": "Operator Health Impact Alerts",
     "type": "table",
     "gridPos": { "h": 5, "w": 16, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum(ALERTS{cluster=~\"$cluster\",alertstate=\"firing\",kubernetes_operator_part_of=\"kubevirt\",operator_health_impact=~\"$health_impact\",operator_health_impact!=\"none\", severity=~\"$severity\", severity!=\"info\"}) by (cluster,alertname,alertstate,severity,namespace,name,operator_health_impact)"
      }
     ]
    },
    {
     "title": "Operator CSV Issues",
     "type": "table",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
     "targets": [
      {
       "expr": "count by (version,phase, reason) (csv_abnormal{name=~\".*hyperconverged.*\",cluster=~\"$cluster\"}>0)",
       "legendFormat": "{{version}}"
      }
     ]
    },
    {
     "title": "All Alerts",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "sum(ALERTS{cluster=~\"$cluster\",alertstate=\"firing\",kubernetes_operator_part_of=\"kubevirt\",operator_health_impact=~\"$health_impact\", severity=~\"$severity\"}) by (cluster,alertname,alertstate,severity,namespace,name,operator_health_impact)"
      }
     ]
    }
   ]
  }
 ]
}