{
 "title": "Executive dashboards / Clusters Overview",
 "description": "This dashboard provides insights for the health of the OpenShift Virtualization operator and displays key metrics for virtual machines at the cluster level across multiple clusters. It helps monitor and assess the status of virtualization resources, ensuring ease of operation and quick identification of issues.",
 "tags": [
  "OpenShift",
  "Virtualization",
  "ACM",
  "KubeVirt"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubevirt_hyperconverged_operator_health_status, cluster)"
    }
   },
   {
    "name": "operator_health",
    "label": "Operator Health",
    "query": "Healthy : ==0, Warning : ==1, Critical : ==2"
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Clusters",
   "type": "stat",
   "description": "Total clusters with OpenShift Virtualization.",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (\nlabel_replace(sum by (name, openshiftVersion) (acm_managed_cluster_labels{name=~\"$cluster\"}), \"cluster\", \"$1\", \"name\", \"(.*)\") + \non(cluster) group_left()(max by (cluster)(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}*0))\n)"
    }
   ]
  },
  {
   "title": "Clusters in Critical Health",
   "type": "stat",
   "description": "Total number of clusters with critical issues that impact the operator health, which are based on alerts and the operator conditions. This means there is a risk of core functionality loss for your clusters.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by (cluster)(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}) == 2) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Allocatable Nodes",
   "type": "stat",
   "description": "Total number of nodes that are available to host virtual machines.",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (cluster) (count(kube_node_status_allocatable{resource=~\".*kubevirt.*\", cluster!~\"local-cluster\"}) by (cluster,node)))"
    }
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "description": "Total number of virtual machines.",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(kubevirt_vm_info{cluster=~\"$cluster\"}) by (name))"
    }
   ]
  },
  {
   "title": "Virtual Machines by Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum(kubevirt_vm_info{cluster=~\"$cluster\", status_group=\"running\"}>0) by (status_group) or vector(0))",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(sum(kubevirt_vm_info{cluster=~\"$cluster\", status_group=\"non_running\"}>0) by (status_group) or vector(0))",
     "legendFormat": "Stopped"
    },
    {
     "expr": "sum(sum(kubevirt_vm_info{cluster=~\"$cluster\", status_group=\"error\"}>0) by (status_group) or vector(0))",
     "legendFormat": "Error"
    },
    {
     "expr": "sum(sum(kubevirt_vm_info{cluster=~\"$cluster\", status_group=\"starting\"}>0) by (status_group) or vector(0))",
     "legendFormat": "Starting"
    },
    {
     "expr": "sum(sum(kubevirt_vm_info{cluster=~\"$cluster\", status_group=\"migrating\"}>0) by (status_group) or vector(0))",
     "legendFormat": "Migrating"
    }
   ]
  },
  {
   "title": "Clusters in Warning Health",
   "type": "stat",
   "description": "Total number of clusters with warning level issues that impact the operator health, which are based on alerts and the operator conditions. This means there is a risk of core functionality loss for your clusters.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max by (cluster)(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}) == 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Number of VMs Started in the last 7 days",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (cluster)(time() - (label_replace(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}>0 ,\"status\",\"starting\",\"\",\"\")) < 604800)"
    }
   ]
  },
  {
   "title": "Clusters by Operator Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "count by (version)(count by (cluster, version) (csv_succeeded{name=~\".*hyperconverged.*\",cluster=~\"$cluster\"}>0)) or (count by (version,phase, reason)(count by (cluster, version,phase, reason) (csv_abnormal{name=~\".*hyperconverged.*\",cluster=~\"$cluster\"}>0)))",
     "legendFormat": "{{version}}"
    },
    {
     "expr": "count by (version)(\n    count by (cluster, version) (csv_succeeded{name=~\".*hyperconverged.*\",cluster=~\"$cluster\"})\n)/\n(count by (version) (csv_succeeded{name=~\".*hyperconverged.*\"}))"
    }
   ]
  },
  {
   "title": "Clusters by OpenShift Version",
   "type": "table",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "expr": "count by (openshiftVersion)(\nlabel_replace(sum by (name, openshiftVersion) (acm_managed_cluster_labels{name=~\"$cluster\"}), \"cluster\", \"$1\", \"name\", \"(.*)\") + \non(cluster) group_left()(max by (cluster)(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}*0))\n)",
     "legendFormat": "{{openshiftVersion}}"
    },
    {
     "expr": "count by (openshiftVersion)(count by (cluster, openshiftVersion)(\nlabel_replace(sum by (name, openshiftVersion) (acm_managed_cluster_labels{name=~\"$cluster\"}), \"cluster\", \"$1\", \"name\", \"(.*)\") + \non(cluster) group_left()(max by (cluster)(kubevirt_hyperconverged_operator_health_status*0))\n)) \n/ scalar(count(count by (cluster, openshiftVersion)(\nlabel_replace(sum by (name, openshiftVersion) (acm_managed_cluster_labels{name=~\"$cluster\"}), \"cluster\", \"$1\", \"name\", \"(.*)\") + \non(cluster) group_left()(max by (cluster)(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}*0))\n)))"
    }
   ]
  },
  {
   "title": "Operator Health",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operator Health by Cluster",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "max by (cluster)(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}$operator_health)"
      },
      {
       "expr": "(sum(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}$operator_health) by (cluster))*0 + on (cluster) group_left() (sum by (cluster)(ALERTS{kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\",cluster=~\"$cluster\",operator_health_impact=\"critical\"}) or \n (sum by (cluster)(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}*0)))"
      },
      {
       "expr": "(sum(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}$operator_health) by (cluster))*0 + on (cluster) group_left() (sum by (cluster)(ALERTS{kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\",cluster=~\"$cluster\",operator_health_impact=\"warning\"}) or (sum by (cluster)(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}*0)))"
      },
      {
       "expr": "(sum(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}$operator_health) by (cluster))*0 + on (cluster) group_left() (sum by (cluster)(cnv:vmi_status_running:count{cluster=~\"$cluster\"})) or ((sum(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"}$operator_health) by (cluster))*0)"
      },
      {
       "expr": "sum by (cluster)(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"} $operator_health) * 0 \n+ on(cluster) (sum by (cluster)(kubevirt_hco_system_health_status{cluster=~\"$cluster\"}))"
      }
     ]
    }
   ]
  },
  {
   "title": "Additional Virtual Machines Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Running VMs by OS",
     "type": "piechart",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (os)(max by (cluster, namespace, name, os)(label_replace(kubevirt_vmi_info{cluster=~\"$cluster\", guest_os_name!=\"\", phase=\"running\"}, \"os\", \"$1\", \"guest_os_name\", \"(.*)\")\n+ on (cluster, namespace, name) group_left()(0*(kubevirt_vm_info{cluster=~\"$cluster\", status_group=\"running\"}>0))))"
      },
      {
       "expr": "sum by (os)(max by (cluster, namespace, name, os)(label_replace(kubevirt_vmi_info{cluster=~\"$cluster\", guest_os_name=\"\", phase=\"running\"}, \"os\", \"unknown\", \"guest_os_name\", \"\")\n+ on (cluster, namespace, name) group_left()(0*(kubevirt_vm_info{cluster=~\"$cluster\", status_group=\"running\"}>0)))\nunless on (cluster, namespace, name)\nmax by (cluster, namespace, name)(kubevirt_vmi_info{cluster=~\"$cluster\", guest_os_name!=\"\", phase=\"running\"}))"
      }
     ]
    },
    {
     "title": "Running VMs by Cluster - Top 20",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sum by (cluster) (kubevirt_vm_info{cluster=~\"$cluster\", status_group=\"running\"} > 0))",
       "legendFormat": "{{cluster}} "
      }
     ]
    },
    {
     "title": "Virtual Machines by Status",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(sum(kubevirt_vm_info{cluster=~\"$cluster\", status_group=\"running\"}>0) by (status_group) or vector(0))",
       "legendFormat": "running"
      },
      {
       "expr": "sum(sum(kubevirt_vm_info{cluster=~\"$cluster\", status_group=\"starting\"}>0) by (status_group) or vector(0))",
       "legendFormat": "starting"
      },
      {
       "expr": "sum(sum(kubevirt_vm_info{cluster=~\"$cluster\", status_group=\"migrating\"}>0) by (status_group) or vector(0))",
       "legendFormat": "migrating"
      },
      {
       "expr": "sum(sum(kubevirt_vm_info{cluster=~\"$cluster\", status_group=\"error\"}>0) by (status_group) or vector(0))",
       "legendFormat": "error"
      },
      {
       "expr": "sum(sum(kubevirt_vm_info{cluster=~\"$cluster\", status_group=\"non_running\"}>0) by (status_group) or vector(0))",
       "legendFormat": "stopped"
      }
     ]
    },
    {
     "title": "Running VMs by Node - Top 20",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "topk(20, sum(kubevirt_vmi_phase_count{cluster=~\"$cluster\",namespace=~\".*\", phase=~\"running\"}) by (cluster,phase,node))",
       "legendFormat": "{{cluster}} | {{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Utilization - Top 20",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage by Cluster",
     "type": "timeseries",
     "description": "This panel displays the top 20 clusters based on their VMs CPU usage over the past 10 minutes. CPU usage is calculated as the total CPU time consumed by VMs. This provides insight into clusters with the highest CPU demand and helps identify potential resource bottlenecks.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(20, sum(rate(kubevirt_vmi_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\"}[10m])) by (cluster))",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Clusters by CPU Usage (%)",
     "type": "timeseries",
     "description": "This panel displays the top 20 clusters based on their CPU usage percentage for clusters running virtual machines (VMs) over the past 10 minutes. CPU usage is calculated as the total CPU time consumed by VMs divided by the total CPU capacity of nodes actively hosting VMs. This provides insight into clusters with the highest CPU demand and helps identify potential resource bottlenecks.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(20,sum by(cluster)(rate(kubevirt_vmi_cpu_usage_seconds_total{cluster=~\"$cluster\"}[10m]))/\n(sum by(cluster)(rate(node_cpu_seconds_total{cluster=~\"$cluster\"}[10m]))))",
       "legendFormat": "{{cluster}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization - Top 20",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage by Cluster",
     "type": "timeseries",
     "description": "Top 20 Clusters based on the VMs memory usage in the clusters",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20, sum by (cluster)(\n  kubevirt_vmi_memory_used_bytes{cluster=~\"$cluster\"}\n  )\n)",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Memory Usage by Cluster (%)",
     "type": "timeseries",
     "description": "Top 20 Clusters based on the VMs memory usage percentage out of the total memory available in the cluster.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "topk(20,(\n  sum by (cluster) (\n    kubevirt_vmi_memory_used_bytes{cluster=~\"$cluster\"}\n  )\n  /\n  (sum by (cluster)(label_replace(node_memory_MemTotal_bytes{cluster=~\"$cluster\"}, \"node\", \"$1\", \"instance\", \"(.*)\")))\n )\n)",
       "legendFormat": "{{cluster}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network Utilization - Top 20",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Clusters by Network Received Bytes",
     "type": "timeseries",
     "description": "This panel displays the top 20 clusters by network received bytes per second over the past 10 minutes. The query measures the rate of incoming network traffic, helping identify VMs with the highest network activity. Use this information to monitor and optimize resource usage for workloads with significant data reception.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20,sum(rate(kubevirt_vmi_network_receive_bytes_total{cluster=~\"$cluster\"}[10m])) by (cluster))",
       "legendFormat": "{{cluster}} - Receive"
      }
     ]
    },
    {
     "title": "Clusters by Network Transmitted Bytes",
     "type": "timeseries",
     "description": "This panel displays the top 20 clusters by network transmitted bytes per second over the past 10 minutes. The query measures the rate of incoming network traffic, helping identify VMs with the highest network activity. Use this information to monitor and optimize resource usage for workloads with significant data reception.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20,sum(rate(kubevirt_vmi_network_transmit_bytes_total{cluster=~\"$cluster\"}[10m])) by (cluster))",
       "legendFormat": "{{cluster}} - Transmit"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage Utilization - Top 20",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Traffic by Cluster",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "topk(20, sum by (cluster)(rate(kubevirt_vmi_storage_read_traffic_bytes_total{cluster=~\"$cluster\"}[10m]) + rate(kubevirt_vmi_storage_write_traffic_bytes_total{cluster=~\"$cluster\"}[10m])))",
       "legendFormat": "{{cluster}}"
      }
     ]
    },
    {
     "title": "Storage IOPs by Cluster",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "topk(20, sum by (cluster) (rate(kubevirt_vmi_storage_iops_read_total{cluster=~\"$cluster\"}[10m]) + rate(kubevirt_vmi_storage_iops_write_total{cluster=~\"$cluster\"}[10m])))",
       "legendFormat": "{{cluster}}"
      }
     ]
    }
   ]
  }
 ]
}