{
 "title": "Executive dashboards / Load Aware Rebalancing",
 "description": "This dashboard provides insights for the behaviour of the Descheduler used to rebalance OpenShift Virtualization workloads according to real load.",
 "tags": [
  "OpenShift",
  "Virtualization",
  "ACM",
  "KubeVirt"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "threshold", "query": "0.1" },
   {
    "name": "node",
    "query": {
     "query": "label_values(kube_node_labels{label_kubevirt_io_schedulable=\"true\"},node)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Node classification", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster average CPU utilization (workers)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "descheduler:averageworkersutilization:cpu:avg1m{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Standard deviation of CPU utilization (workers)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "stddev(descheduler:nodeutilization:cpu:avg1m * on(instance) group_left(node) label_replace(kube_node_role{role=\"worker\"}, 'instance', \"$1\", 'node', '(.+)'))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Combined CPU utilization & PSI pressure by node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "descheduler:averageworkersutilization:cpu:avg1m",
     "legendFormat": "Average CPU utilization"
    },
    {
     "expr": "descheduler:nodeutilization:cpu:avg1m{instance=~\"$node\"} * on(instance) group_left(node) label_replace(kube_node_role{role=\"worker\"}, 'instance', \"$1\", 'node', '(.+)')",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "descheduler:averageworkersutilization:cpu:avg1m + $threshold",
     "legendFormat": "threshold"
    },
    { "expr": " + 1", "legendFormat": "top" },
    { "expr": " + 0", "legendFormat": "base" }
   ]
  },
  {
   "title": "Allocatable Nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(descheduler:nodeutilization:cpu:avg1m{instance=~\"$node\"} * on(instance) group_left(node) label_replace(kube_node_role{role=\"worker\"}, 'instance', \"$1\", 'node', '(.+)'))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Over utilized nodes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((descheduler:nodeutilization:cpu:avg1m{instance=~\"$node\"} > on() group_left() descheduler:averageworkersutilization:cpu:avg1m + 0.1) * on(instance) group_left(node) label_replace(kube_node_role{role=\"worker\"}, 'instance', \"$1\", 'node', '(.+)')) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node classification by utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count((descheduler:nodeutilization:cpu:avg1m{instance=~\"$node\"} < on() group_left() descheduler:averageworkersutilization:cpu:avg1m) * on(instance) group_left(node) label_replace(kube_node_role{role=\"worker\"}, 'instance', \"$1\", 'node', '(.+)')) or vector(0)",
     "legendFormat": "under utilized"
    },
    { "expression": "$NODES-$OVER-$UNDER", "type": "math" },
    {
     "expr": "count((descheduler:nodeutilization:cpu:avg1m{instance=~\"$node\"} > on() group_left() descheduler:averageworkersutilization:cpu:avg1m + $threshold) * on(instance) group_left(node) label_replace(kube_node_role{role=\"worker\"}, 'instance', \"$1\", 'node', '(.+)')) or vector(0)",
     "legendFormat": "over utilized"
    },
    {
     "expr": "count(descheduler:nodeutilization:cpu:avg1m{instance=~\"$node\"} * on(instance) group_left(node) label_replace(kube_node_role{role=\"worker\"}, 'instance', \"$1\", 'node', '(.+)'))",
     "legendFormat": "nodes"
    }
   ]
  },
  { "title": "CPU Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "CPU utilization for VMs by node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node) (\n  (\n    sum by (cluster, namespace, pod) (\n      avg_over_time(\n        node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=~\"virt-launcher.*\", node=~\"$node\"}[5m]\n      )\n    )\n    *\n    on (cluster, namespace, pod) group_left(node)\n    topk by (cluster, namespace, pod) (\n      1,\n      max by (cluster, namespace, pod, node) (\n        kube_pod_info{node!=\"\"}\n      )\n    )\n  )\n  /\n  on (node) group_left\n  machine_cpu_cores\n  *\n  on (node) group_left\n  kube_node_labels{label_kubevirt_io_schedulable=\"true\"}\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU utilization for non VM pods by node",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (node) (\n  (\n    sum by (cluster, namespace, pod) (\n      avg_over_time(\n        node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod!~\"virt-launcher.*\", node=~\"$node\"}[5m]\n      )\n    )\n    *\n    on (cluster, namespace, pod) group_left(node)\n    topk by (cluster, namespace, pod) (\n      1,\n      max by (cluster, namespace, pod, node) (\n        kube_pod_info{node!=\"\"}\n      )\n    )\n  )\n  /\n  on (node) group_left\n  machine_cpu_cores\n  *\n  on (node) group_left\n  kube_node_labels{label_kubevirt_io_schedulable=\"true\"}\n)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "PSI Pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster average PSI CPU pressure (workers)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(descheduler:nodepressure:cpu:avg1m * on(instance) \n  group_left() \n  label_replace(\n    kube_node_role{role=\"worker\"}, \n    'instance', '$1', \n    'node', '(.+)'\n  ))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Standard deviation of PSI CPU pressure (workers)",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "stddev(descheduler:nodepressure:cpu:avg1m * on(instance) group_left(node) label_replace(kube_node_role{role=\"worker\"}, 'instance', \"$1\", 'node', '(.+)'))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "PSI CPU pressure by Worker Node",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "descheduler:nodepressure:cpu:avg1m{instance=~\"$node\"} * on(instance) \n  group_left() \n  label_replace(\n    kube_node_role{role=\"worker\"}, \n    'instance', '$1', \n    'node', '(.+)'\n  )",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  { "title": "VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "VM Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_vmi_phase_count{phase=~\"running\",node=~\"$node\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Migration rate (10m)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(sum(kubevirt_vmi_migration_succeeded)[10m:])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VMI Running by Nodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kubevirt_vmi_phase_count{namespace=~\".*\", phase=~\"running\", node=~\"$node\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Top Consumers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Top consumers - VMs (% of CPU utilization on the node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort_desc(topk(10,\n  (\n    sum by (cluster, namespace, pod) (\n      avg_over_time(\n        node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod=~\"virt-launcher.*\", node=~\"$node\"}[5m]\n      )\n    )\n    *\n    on (cluster, namespace, pod) group_left(node)\n    topk by (cluster, namespace, pod) (\n      1,\n      max by (cluster, namespace, pod, node) (\n        kube_pod_info{node!=\"\"}\n      )\n    )\n  )\n  /\n  on (node) group_left\n  machine_cpu_cores\n  *\n  on (node) group_left\n  kube_node_labels{label_kubevirt_io_schedulable=\"true\"}\n))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Top consumers - other pods (% of CPU utilization on the node)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort_desc(topk(10,\n  (\n    sum by (cluster, namespace, pod) (\n      avg_over_time(\n        node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{pod!~\"virt-launcher.*\", node=~\"$node\"}[5m]\n      )\n    )\n    *\n    on (cluster, namespace, pod) group_left(node)\n    topk by (cluster, namespace, pod) (\n      1,\n      max by (cluster, namespace, pod, node) (\n        kube_pod_info{node!=\"\"}\n      )\n    )\n  )\n  /\n  on (node) group_left\n  machine_cpu_cores\n  *\n  on (node) group_left\n  kube_node_labels{label_kubevirt_io_schedulable=\"true\"}\n))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}