{
 "title": "Service Level dashboards / Virtual Machines Service Level",
 "description": "This dashboard provides an overview of the Virtual Machines uptime, planned and unplanned downtime.",
 "tags": [
  "Virtualization",
  "OpenShift",
  "ACM",
  "KubeVirt"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubevirt_vm_running_status_last_transition_timestamp_seconds, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kubevirt_vmi_info, namespace)"
    }
   },
   {
    "name": "name",
    "label": "VM Name",
    "query": {
     "query": "label_values(kubevirt_vmi_info, name)"
    }
   },
   {
    "name": "status",
    "label": "Status",
    "query": "All : on(cluster\\,name\\,namespace) group_left()(0*(sum by(cluster\\,namespace\\,name)(kubevirt_vm_info))), stopped : on(cluster\\,name\\,namespace) group_left()(0*(sum by(cluster\\,namespace\\,name)(kubevirt_vm_info{status_group=\"non_running\"}>0))), starting : on(cluster\\,name\\,namespace) group_left()(0*(sum by(cluster\\,namespace\\,name)(kubevirt_vm_info{status_group=\"starting\"} > 0))), migrating : on(cluster\\, name\\, namespace) group_left() (0*(sum by (cluster\\, namespace\\, name)(kubevirt_vm_info{status_group=\"migrating\"}>0))), error : on(cluster\\,name\\,namespace) group_left()(0*(sum by(cluster\\,namespace\\,name)(kubevirt_vm_info{status_group=\"error\"}>0))), running : on(cluster\\,name\\,namespace) group_left()(0*(sum by(cluster\\,namespace\\,name)(kubevirt_vm_info{status_group=\"running\"}>0)))"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Uptime %",
   "type": "stat",
   "description": "The total uptime % of the VMs that are listed in the dashboard",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", status_group=~\"running\"} > bool 0) \n    [$__range:5m]\n    ))\n    +${status:raw}\n)/ \n(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"} > bool 0) \n    [$__range:5m]\n    ))\n    +${status:raw}\n)"
    }
   ]
  },
  {
   "title": "Total Planned Downtime %",
   "type": "stat",
   "description": "The total planned downtime % of the VMs that are listed in the dashboard",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", status_group=~\"starting|migrating|non_running\"} > bool 0) \n    [$__range:5m]\n    ))\n    +${status:raw}\n)/ \n(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"} > bool 0) \n    [$__range:5m]\n    ))\n    +${status:raw}\n)"
    }
   ]
  },
  {
   "title": "Total Unplanned Downtime %",
   "type": "stat",
   "description": "The total unplanned downtime of the VMs that are listed in the dashboard",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", status_group=~\"error\"} > bool 0) \n    [$__range:5m]\n    ))\n    +${status:raw}\n)/ \n(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"} > bool 0) \n    [$__range:5m]\n    ))\n    +${status:raw}\n)"
    }
   ]
  },
  {
   "title": "Total Uptime (Hours)",
   "type": "stat",
   "description": "The total uptime of the VMs that are listed in the dashboard",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", status_group=~\"running\"} > bool 0) \n    [$__range:5m]\n    ) *300 )\n    +${status:raw}\n)/3600"
    }
   ]
  },
  {
   "title": "Total Planned Downtime (Hours)",
   "type": "stat",
   "description": "The total planned downtime of the VMs that are listed in the dashboard",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", status_group=~\"starting|migrating|non_running\"} > bool 0) \n    [$__range:5m]\n    ) *300 )\n    +${status:raw}\n)/3600"
    }
   ]
  },
  {
   "title": "Total Unplanned Downtime (Hours)",
   "type": "stat",
   "description": "The total unplanned downtime of the VMs that are listed in the dashboard",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", status_group=~\"error\"} > bool 0) \n    [$__range:5m]\n    ) *300 )\n    +${status:raw}\n)/3600"
    }
   ]
  },
  {
   "title": "Virtual Machines List by Time In Status",
   "type": "table",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by (cluster, namespace, name, status_group)(kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"})+${status:raw}"
    },
    {
     "expr": "(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", status_group=~\"starting|migrating|non_running\"} > bool 0) \n    [$__range:5m]\n    ) *300 )\n    +${status:raw}\n)/3600"
    },
    {
     "expr": "(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", status_group=~\"starting|migrating|non_running\"} > bool 0) \n    [$__range:5m]\n    ))\n    +${status:raw}\n)/ \n(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"} > bool 0) \n    [$__range:5m]\n    ))\n    +${status:raw}\n)"
    },
    {
     "expr": "(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", status_group=~\"error\"} > bool 0) \n    [$__range:5m]\n    ) *300)\n    +${status:raw}\n)/3600"
    },
    {
     "expr": "(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", status_group=~\"error\"} > bool 0) \n    [$__range:5m]\n    ))\n    +${status:raw}\n)/ \n(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"} > bool 0) \n    [$__range:5m]\n    ))\n    +${status:raw}\n)"
    },
    {
     "expr": "((kubevirt_vm_create_date_timestamp_seconds{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"}>0) *1000 )+${status:raw}"
    },
    {
     "expr": "(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", status_group=~\"running\"} > bool 0) \n    [$__range:5m]\n    ) *300 )\n    +${status:raw}\n)/3600"
    },
    {
     "expr": "(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", status_group=~\"running\"} > bool 0) \n    [$__range:5m]\n    ))\n    +${status:raw}\n)/ \n(\n  sum by (cluster, name , namespace)(\n    sum_over_time(\n    (kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"} > bool 0) \n    [$__range:5m]\n    ))\n    +${status:raw}\n)"
    },
    {
     "expr": "sum by (cluster, namespace, name, status)(kubevirt_vm_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", status_group=\"error\"})+${status:raw}"
    }
   ]
  }
 ]
}