apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  instanceSize: minimal
  observabilityAddonSpec: {}
  capabilities:
    platform:
      metrics:
        default:
          enabled: true
  storageConfig:
    metricObjectStorage:
      name: thanos-object-storage
      key: thanos.yaml
    compactStorageSize: 10Gi
    receiveStorageSize: 10Gi
    ruleStorageSize: 10Gi
    storeStorageSize: 10Gi
