{
 "title": "OpenShift Virtualization - General View",
 "tags": [
  "Openshift",
  "Virtualization",
  "KubeVirt",
  "ACM",
  "General-View"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster_old",
    "label": "Cluster_old",
    "query": {
     "query": "label_values(csv_succeeded{name=~\".*hyperconverged.*\"},cluster)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kubevirt_hyperconverged_operator_health_status{name=~\".*hyperconverged.*\"},cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Openshift Version",
   "type": "table",
   "description": "For a detailed single-cluster view, click on the cluster name below.",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "count by (name,openshiftVersion) (acm_managed_cluster_labels{name=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "description": "Total number of nodes available to host virtual machines",
   "gridPos": { "h": 6, "w": 3, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (cluster) (count(kube_node_status_allocatable{resource=~\".*kubevirt.*\", cluster!~\"local-cluster\"}) by (cluster,node)))"
    }
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "description": "Total number of Virtual Machines",
   "gridPos": { "h": 6, "w": 3, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(kubevirt_vm_error_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}) by (name))"
    }
   ]
  },
  {
   "title": "Running VMs ",
   "type": "stat",
   "description": "Total number of Virtual Machines with a 'running' status",
   "gridPos": { "h": 6, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cnv:vmi_status_running:count{cluster=~\"$cluster\", namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Non-running VMs",
   "type": "stat",
   "description": "Total number of Virtual Machines with a non-running status",
   "gridPos": { "h": 6, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} == 0 ) by (cluster))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "VMs started in the last 7 days",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, count by (cluster) (increase(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}[7d]) > time()))"
    }
   ]
  },
  {
   "title": "Running VMs (Timeline)",
   "type": "timeseries",
   "description": "Top 20 Clusters",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(20, sum by (cluster) (cnv:vmi_status_running:count{cluster=~\".*\", namespace=~\".*\"}))",
     "legendFormat": "{{cluster}} "
    }
   ]
  },
  {
   "title": "VMs by Phase",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count(kubevirt_vm_starting_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
     "legendFormat": "starting"
    },
    {
     "expr": "sum(count(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
     "legendFormat": "running"
    },
    {
     "expr": "sum(count(kubevirt_vm_migrating_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
     "legendFormat": "migrating"
    },
    {
     "expr": "sum(count(kubevirt_vm_error_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
     "legendFormat": "error"
    },
    {
     "expr": "sum(count(kubevirt_vm_non_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
     "legendFormat": "stopped"
    }
   ]
  },
  {
   "title": "Running VMs by Node",
   "type": "timeseries",
   "description": "Top 50 Nodes",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(50, sum(kubevirt_vmi_phase_count{cluster=~\"$cluster\",namespace=~\".*\", phase=~\"running\"}) by (cluster,phase,node))",
     "legendFormat": "{{cluster}} | {{node}}"
    }
   ]
  },
  {
   "title": "Running VMs by OS",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_vmi_phase_count{cluster=~\"$cluster\",namespace=~\".*\", phase=~\"running\"}) by (phase,os)",
     "legendFormat": "{{os}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU Usage by Cluster",
   "type": "timeseries",
   "description": "Top 20 Clusters",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(20, sum(rate(kubevirt_vmi_cpu_user_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\"}[1h])) by (cluster))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Cluster",
   "type": "timeseries",
   "description": "Top 20 Clusters",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20, sum(rate(kubevirt_vmi_memory_used_bytes{cluster=~\"$cluster\",namespace=~\".*\"}[1h])) by (cluster))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Network Usage by Cluster",
   "type": "timeseries",
   "description": "Top 20 Clusters",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(20,sum(rate(kubevirt_vmi_network_receive_bytes_total{cluster=~\"$cluster\"}[1h])) by (cluster))",
     "legendFormat": "{{cluster}} - Receive"
    },
    {
     "expr": "topk(20,sum(rate(kubevirt_vmi_network_transmit_bytes_total{cluster=~\"$cluster\"}[1h])) by (cluster))",
     "legendFormat": "{{cluster}} - Transmit"
    }
   ]
  },
  {
   "title": "Storage IOPs by Cluster",
   "type": "timeseries",
   "description": "Top 20 Clusters",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk(20, sum by (cluster) (rate(kubevirt_vmi_storage_iops_read_total{cluster=~\"$cluster\",drive=\"rootdisk\"}[12h]) + rate(kubevirt_vmi_storage_iops_write_total{cluster=~\"$cluster\",drive=\"rootdisk\"}[12h])))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  { "title": "Operator Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Critical Severity Alerts",
   "type": "stat",
   "description": "Total number of alerts that are firing with the severity level: critical.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (ALERTS{kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\",cluster=~\"$cluster\",severity=\"critical\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Warning Severity Alerts",
   "type": "stat",
   "description": "Total number of alerts that are firing with the severity level: warning.",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (ALERTS{kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\",cluster=~\"$cluster\",severity=\"warning\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Info Severity Alerts",
   "type": "stat",
   "description": "Total number of alerts that are firing with the severity level: warning.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (ALERTS{kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\",cluster=~\"$cluster\",severity=\"info\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Kubevirt Alerts",
   "type": "table",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum(rate(ALERTS{cluster=~\"$cluster\",alertstate=\"firing\",kubernetes_operator_part_of=\"kubevirt\",severity!~\"info|none\"}[15m])) by (cluster,alertname,alertstate,severity,namespace,name)"
    }
   ]
  },
  {
   "title": "Total Kubevirt Alerts by Cluster",
   "type": "table",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 55 },
   "targets": [
    {
     "expr": "sum by (cluster,alertstate,severity) (count(rate(ALERTS{cluster=~\".*\",alertstate=\"firing\",kubernetes_operator_part_of=\"kubevirt\"}[15m])) by (cluster,alertname,alertstate,severity,name))"
    }
   ]
  }
 ]
}