{
 "title": "OpenShift Virtualization - Single-Cluster View",
 "tags": [
  "Openshift",
  "Virtualization",
  "KubeVirt",
  "ACM",
  "Single-Cluster"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kubevirt_hyperconverged_operator_health_status{name=~\".*hyperconverged.*\"},cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubevirt_hyperconverged_operator_health_status{name=~\".*hyperconverged.*\", cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Openshift Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(acm_managed_cluster_labels{name=~\"$cluster\"}) by (openshiftVersion)"
    }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "stat",
   "description": "Total node count in OpenShift Virtualization clusters",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count by (cluster) (count(kube_node_status_allocatable{resource=~\".*kubevirt.*\", cluster=~\"$cluster\"}) by (cluster,node)))"
    }
   ]
  },
  {
   "title": "Total VMs",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count(kubevirt_vm_error_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}) by (name))"
    }
   ]
  },
  {
   "title": "Running VMs ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(cnv:vmi_status_running:count{cluster=~\"$cluster\", namespace=~\".*\"})"
    }
   ]
  },
  {
   "title": "Non-running VMs ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} == 0 ) by (cluster)"
    }
   ]
  },
  {
   "title": "VMs started in the last 7 day",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "bottomk(4, sum by (name) (sort(time() - kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}) / 1 ))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Provider",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(acm_managed_cluster_labels{name=~\"$cluster\"}) by (cloud)"
    }
   ]
  },
  {
   "title": "Openshift Virt Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "csv_succeeded{name=~\".*hyperconverged.*\", cluster=~\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Operator Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (cluster)(kubevirt_hyperconverged_operator_health_status{cluster=~\"$cluster\"})*0 or on(cluster) (kubevirt_hco_system_health_status{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total VMs Running (Timeline)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (cluster) (cnv:vmi_status_running:count{cluster=~\"$cluster\", namespace=~\".*\"})",
     "legendFormat": "{{cluster}} "
    }
   ]
  },
  {
   "title": "VMs by Phase",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(count(kubevirt_vm_starting_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
     "legendFormat": "starting"
    },
    {
     "expr": "sum(count(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
     "legendFormat": "running"
    },
    {
     "expr": "sum(count(kubevirt_vm_migrating_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
     "legendFormat": "migrating"
    },
    {
     "expr": "sum(count(kubevirt_vm_error_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
     "legendFormat": "error"
    },
    {
     "expr": "sum(count(kubevirt_vm_non_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"} > 0)) or vector(0)",
     "legendFormat": "stopped"
    }
   ]
  },
  {
   "title": "VMs Running by Node",
   "type": "timeseries",
   "description": "Top 50 nodes",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(50, sum(kubevirt_vmi_phase_count{cluster=~\"$cluster\",namespace=~\".*\", phase=~\"running\"}) by (cluster,phase,node))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Virtual Machines by OS",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubevirt_vmi_phase_count{cluster=~\"$cluster\",namespace=~\".*\", phase=~\"running\"}) by (phase,os)",
     "legendFormat": "{{os}}"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "CPU Usage by Nodes",
   "type": "timeseries",
   "description": "Top 50 nodes",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(50,sum(label_replace(rate(instance:node_cpu_utilisation:rate1m{cluster=~\"$cluster\"}[1h]), \"node\", \"$1\", \"instance\", \"(.*)\")) by (node, cluster)\n* on(node, cluster) group_left()\nsum(kubevirt_vmi_cpu_user_usage_seconds_total{cluster=~\"$cluster\"}) by (node, cluster))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU Usage by VM",
   "type": "timeseries",
   "description": "Top 50 VMs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(50,sum by (name) (rate(kubevirt_vmi_cpu_usage_seconds_total{cluster=~\"$cluster\",namespace=~\".*\"}[1h])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage by Nodes",
   "type": "timeseries",
   "description": "Top 50 nodes with virtualization workloads",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(50,sum(label_replace(rate(instance:node_memory_utilisation:ratio{cluster=~\"$cluster\"}[1h]), \"node\", \"$1\", \"instance\", \"(.*)\")) by (node, cluster)\n* on(node, cluster) group_left()\nsum(kubevirt_vmi_memory_used_bytes{cluster=~\"$cluster\"}) by (node, cluster))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory Usage by VM",
   "type": "timeseries",
   "description": "Top 50 VMs ",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(50,sum by (name) (rate(kubevirt_vmi_memory_used_bytes{cluster=~\"$cluster\",namespace=~\".*\"}[1h])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Usage by Nodes",
   "type": "timeseries",
   "description": "Top 50 nodes",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(50,sum(label_replace(rate(instance:node_network_receive_bytes_excluding_lo:rate1m{cluster=\"rosa-hcp\"}[1h]), \"node\", \"$1\", \"instance\", \"(.*)\")) by (node, cluster)\n* on(node, cluster) group_left()\nsum(kubevirt_vmi_network_receive_packets_total{cluster=\"rosa-hcp\"}) by (node, cluster))",
     "legendFormat": "{{node}} - Receive"
    },
    {
     "expr": "topk(50,sum(label_replace(rate(instance:node_network_transmit_bytes_excluding_lo:rate1m{cluster=\"rosa-hcp\"}[1h]), \"node\", \"$1\", \"instance\", \"(.*)\")) by (node, cluster)\n* on(node, cluster) group_left()\nsum(kubevirt_vmi_network_transmit_packets_total{cluster=\"rosa-hcp\"}) by (node, cluster))",
     "legendFormat": "{{node}} - Transmit"
    }
   ]
  },
  {
   "title": "Network Usage by VM",
   "type": "timeseries",
   "description": "Top 50 VMs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "topk(50,sum(rate(kubevirt_vmi_network_receive_bytes_total{cluster=~\"$cluster\"}[1h])) by (name))",
     "legendFormat": "{{name}} - Receive"
    },
    {
     "expr": "topk(50,sum(rate(kubevirt_vmi_network_transmit_bytes_total{cluster=~\"$cluster\"}[1h])) by (name))",
     "legendFormat": "{{name}} - Transmit"
    }
   ]
  },
  {
   "title": "Storage IOPs by Node",
   "type": "timeseries",
   "description": "Top 50 nodes",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk(50,sum by (node) (rate(kubevirt_vmi_storage_iops_read_total{cluster=~\"$cluster\",drive=\"rootdisk\"}[1h]) + rate(kubevirt_vmi_storage_iops_write_total{cluster=~\"$cluster\",drive=\"rootdisk\"}[1h])))",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Storage IOPs by VM",
   "type": "timeseries",
   "description": "Top 50 VMs",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "topk(50,sum by (name) (rate(kubevirt_vmi_storage_iops_read_total{cluster=~\"$cluster\",drive=\"rootdisk\"}[1h]) + rate(kubevirt_vmi_storage_iops_write_total{cluster=~\"$cluster\",drive=\"rootdisk\"}[1h])))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Operator Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Critical Severity Alerts",
   "type": "stat",
   "description": "Total number of alerts that are firing with the severity level: critical.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (ALERTS{kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\",cluster=~\"$cluster\",severity=\"critical\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Warning Severity Alerts",
   "type": "stat",
   "description": "Total number of alerts that are firing with the severity level: warning.",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (ALERTS{kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\",cluster=~\"$cluster\",severity=\"warning\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Info Severity Alerts",
   "type": "stat",
   "description": "Total number of alerts that are firing with the severity level: warning.",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 75 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (ALERTS{kubernetes_operator_part_of=\"kubevirt\", alertstate=\"firing\",cluster=~\"$cluster\",severity=\"info\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Kubevirt Alerts",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "sum(rate(ALERTS{cluster=~\"$cluster\",alertstate=\"firing\",kubernetes_operator_part_of=\"kubevirt\",severity!~\"info|none\"}[15m])) by (cluster,alertname,alertstate,severity,namespace,name)"
    }
   ]
  }
 ]
}