apiVersion: apps/v1
kind: Deployment
metadata:
  name: multicluster-observability-operator
  namespace: open-cluster-management
spec:
  template:
    spec:
      containers:
      - name: multicluster-observability-operator
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: multicluster-observability-operator-webhook-server-cert
