{
 "title": "ACM Right-Sizing OpenShift Virtualization",
 "tags": [
  "ACM",
  "KubeVirt",
  "Virtualization",
  "Right-Sizing"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"acm_rs_vm:namespace:(cpu_request|cpu_usage|memory_request|memory_usage)\"},cluster)"
    }
   },
   {
    "name": "cpu_profile",
    "label": "CPU Profile",
    "query": {
     "query": "label_values(acm_rs_vm:namespace:cpu_usage{cluster=\"$cluster\"},profile)"
    }
   },
   {
    "name": "memory_profile",
    "label": "Memory Profile",
    "query": {
     "query": "label_values(acm_rs_vm:namespace:memory_usage{cluster=\"$cluster\"},profile)"
    }
   },
   {
    "name": "days",
    "label": "Aggregation",
    "query": "1d, 2d, 5d, 10d, 15d, 30d, 60d, 90d"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values({__name__=~\"acm_rs_vm:namespace:(cpu_request|cpu_usage|memory_request|memory_usage)\",cluster=\"$cluster\",profile=\"$cpu_profile\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total CPU Overestimation",
   "type": "stat",
   "description": "Total CPU Overestimation",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n(floor(max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_request{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:])-\nmax_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_recommendation{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:])) > 0)\nand on (name, namespace) (max by (name, namespace) (kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=\"$cluster\", namespace=~\"$namespace\"} > 0) > 0)\n)"
    }
   ]
  },
  {
   "title": "Total CPU Underestimation",
   "type": "stat",
   "description": "Total CPU Underestimation",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n(floor(max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_request{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:])-\nmax_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_recommendation{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:])) < 0) * (-1)\nand on (name, namespace) (max by (name, namespace) (kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=\"$cluster\", namespace=~\"$namespace\"} > 0) > 0)\n)"
    }
   ]
  },
  {
   "title": "Total Memory Overestimation",
   "type": "stat",
   "description": "Total Memory Overestimation",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n(floor((max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_request{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:]) / 1073741824)-\n(max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_recommendation{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:]) / 1073741824)) > 0)\nand on (name, namespace) (max by (name, namespace) (kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=\"$cluster\", namespace=~\"$namespace\"} > 0) > 0)\n)"
    }
   ]
  },
  {
   "title": "Total Memory Underestimation",
   "type": "stat",
   "description": "Total Memory Underestimation",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(\n(floor((max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_request{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:]) / 1073741824)-\n(max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_recommendation{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:]) / 1073741824)) < 0) * (-1)\nand on (name, namespace) (max by (name, namespace) (kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=\"$cluster\", namespace=~\"$namespace\"} > 0) > 0)\n)"
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "CPU Overestimation",
   "type": "table",
   "description": "CPU Overestimation",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(\n    (\n        max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_usage{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:]) / max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_request{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:])\n    ) > 0,\n  \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n    (max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_usage{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:])),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n    max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_request{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:]),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n    ceil(max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_recommendation{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:])),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n  (\n    acm_rs_vm:namespace:cpu_usage{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"} + on(name, namespace) acm_rs_vm:namespace:cpu_request{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"}\n  ),\n  \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n    (\n        floor(max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_request{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:])-\n        max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_recommendation{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:]))\n    ),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n  max by (name, namespace) ((kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=\"$cluster\", namespace=~\"$namespace\"} > 0) * 1000),\n  \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    }
   ]
  },
  {
   "title": "CPU Underestimation",
   "type": "table",
   "description": "CPU Underestimation",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(\n    (\n        max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_usage{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:]) / max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_request{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:])\n    ) > 0, \n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n    max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_usage{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:]), \n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n    max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_request{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:]),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n    ceil(max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_recommendation{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:])),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n  (\n    acm_rs_vm:namespace:cpu_usage{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"} + on(name, namespace) acm_rs_vm:namespace:cpu_request{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"}\n  ),\n  \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n    (floor(max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_request{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:])- max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:cpu_recommendation{cluster=\"$cluster\", profile=\"$cpu_profile\", namespace=~\"$namespace\"})[$days:])) * (-1)),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n  max by (name, namespace) ((kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=\"$cluster\", namespace=~\"$namespace\"} > 0) * 1000),\n  \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Overestimation",
   "type": "table",
   "description": "Memory Overestimation",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "label_join(\n    max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_usage{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:]) / max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_request{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:]),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n    (max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_usage{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:]) /1073741824),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n    (max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_request{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:])/1073741824),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n    (ceil(max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_recommendation{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:])/ 1073741824)),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n  (\n    acm_rs_vm:namespace:memory_usage{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"} + on(name, namespace) acm_rs_vm:namespace:memory_request{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"}\n  ),\n  \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n    (floor((max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_request{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:])) / 1073741824 - (max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_recommendation{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:])) / 1073741824)),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n  max by (name, namespace) ((kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=\"$cluster\", namespace=~\"$namespace\"} > 0) * 1000),\n  \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    }
   ]
  },
  {
   "title": "Memory Underestimation",
   "type": "table",
   "description": "Memory Underestimation",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "label_join(\n    (max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_usage{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:]) / max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_request{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:])),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n    (max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_usage{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:])/ 1073741824),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n    (max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_request{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:])/ 1073741824),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n    (ceil(max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_recommendation{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:])/ 1073741824)),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n  (\n    acm_rs_vm:namespace:memory_usage{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"} + on(name, namespace) acm_rs_vm:namespace:memory_request{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"}\n  ),\n  \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n    (floor((max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_request{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:])) / 1073741824 - (max_over_time(sum by (name, namespace) (acm_rs_vm:namespace:memory_recommendation{cluster=\"$cluster\", profile=\"$memory_profile\", namespace=~\"$namespace\"})[$days:])) / 1073741824)* (-1)),\n    \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    },
    {
     "expr": "label_join(\n  max by (name, namespace) ((kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=\"$cluster\", namespace=~\"$namespace\"} > 0) * 1000),\n  \"name_namespace\", \"-\", \"name\", \"namespace\"\n)"
    }
   ]
  }
 ]
}