{
 "title": "ACM GPU Utilization",
 "tags": [
  "ACM",
  "GPU",
  "Right-Sizing"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"acm_rs:cluster:(cpu_request|cpu_usage|memory_request|memory_usage|gpu_request|gpu_usage)\"},cluster)"
    }
   },
   {
    "name": "profile",
    "label": "Profile",
    "query": {
     "query": "label_values({__name__=~\"acm_rs:namespace:(cpu_request|cpu_usage|memory_request|memory_usage|gpu_request|gpu_usage)\",cluster=\"$cluster\"},profile)"
    }
   },
   { "name": "days", "label": "Aggregation", "query": "1d, 2d, 5d, 10d, 30d, 60d, 90d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(acm_rs:workload:gpu_request{cluster=\"$cluster\",profile=\"$profile\"},namespace)"
    }
   },
   {
    "name": "workload_type",
    "label": "Workload Type",
    "query": "Deployment,StatefulSet,DaemonSet,ReplicaSet,Job,CronJob"
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "label_values(acm_rs:pod:gpu_request{cluster=\"$cluster\",namespace=~\"$namespace\",workload_type=~\"$workload_type\",profile=\"$profile\"},workload)"
    }
   }
  ]
 },
 "panels": [
  { "title": "GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GPU Recommendation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum by (cluster)(acm_rs:cluster:gpu_recommendation{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    }
   ]
  },
  {
   "title": "GPU Utilization of Top Namespaces",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 19, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(20,\nsum by (namespace) (acm_rs:namespace:gpu_usage{cluster=\"$cluster\", profile=\"$profile\"})\n/\nsum by (namespace) (acm_rs:namespace:gpu_request{cluster=\"$cluster\", profile=\"$profile\"})\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "GPU Usage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum by (cluster)(acm_rs:cluster:gpu_usage{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    }
   ]
  },
  {
   "title": "GPU Request",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum by (cluster)(acm_rs:cluster:gpu_request{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum by (cluster)(acm_rs:cluster:gpu_usage{cluster=\"$cluster\", profile=\"$profile\"})[$days:]) / max_over_time(sum by (cluster)(acm_rs:cluster:gpu_request{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    }
   ]
  },
  {
   "title": "GPU Quota",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "sort" } },
   "targets": [
    {
     "expr": "max_over_time(sum by (namespace) (acm_rs:namespace:gpu_usage{cluster=\"$cluster\", profile=\"$profile\"})[$days:]) / max_over_time(sum by (namespace) (acm_rs:namespace:gpu_request{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    },
    {
     "expr": "max_over_time(sum by (namespace) (acm_rs:namespace:gpu_usage{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    },
    {
     "expr": "max_over_time(sum by (namespace) (acm_rs:namespace:gpu_request{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    },
    {
     "expr": "max_over_time(sum by (namespace) (acm_rs:namespace:gpu_recommendation{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    }
   ]
  },
  { "title": "GPU Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "GPU Memory Recommendation",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum by (cluster)(acm_rs:cluster:gpu_memory_recommendation{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization of Top Namespaces",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 19, "x": 4, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(20,\nsum by (namespace) (acm_rs:namespace:gpu_memory_used{cluster=\"$cluster\", profile=\"$profile\"})\n/\nsum by (namespace) (acm_rs:namespace:gpu_memory_total{cluster=\"$cluster\", profile=\"$profile\"})\n)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "GPU Memory Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum by (cluster)(acm_rs:cluster:gpu_memory_used{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    }
   ]
  },
  {
   "title": "GPU Memory Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum by (cluster)(acm_rs:cluster:gpu_memory_total{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    }
   ]
  },
  {
   "title": "GPU Memory Utilization",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(sum by (cluster)(acm_rs:cluster:gpu_memory_used{cluster=\"$cluster\", profile=\"$profile\"})[$days:]) / max_over_time(sum by (cluster)(acm_rs:cluster:gpu_memory_total{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    }
   ]
  },
  {
   "title": "GPU Memory Quota",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "max_over_time(sum by (namespace) (acm_rs:namespace:gpu_memory_used{cluster=\"$cluster\", profile=\"$profile\"})[$days:]) / max_over_time(sum by (namespace) (acm_rs:namespace:gpu_memory_total{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    },
    {
     "expr": "max_over_time(sum by (namespace) (acm_rs:namespace:gpu_memory_used{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    },
    {
     "expr": "max_over_time(sum by (namespace) (acm_rs:namespace:gpu_memory_total{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    },
    {
     "expr": "max_over_time(sum by (namespace) (acm_rs:namespace:gpu_memory_recommendation{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    }
   ]
  },
  { "title": "GPU Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "GPU Telemetry (Power / Temperature / Clocks)",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "max_over_time(sum by (namespace) (acm_rs:namespace:gpu_power_usage_watts{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    },
    {
     "expr": "max_over_time(max by (namespace) (acm_rs:namespace:gpu_temperature_celsius{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    },
    {
     "expr": "max_over_time(max by (namespace) (acm_rs:namespace:gpu_sm_clock_hertz{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    },
    {
     "expr": "max_over_time(max by (namespace) (acm_rs:namespace:gpu_memory_clock_hertz{cluster=\"$cluster\", profile=\"$profile\"})[$days:])"
    },
    {
     "expr": "max by (namespace, resource) (max_over_time(acm_rs:namespace:gpu_type{cluster=\"$cluster\", namespace=~\"$namespace\"}[$days:]))"
    }
   ]
  },
  { "title": "Workloads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Workload GPU Quota",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "max_over_time((sum by (workload, namespace) (acm_rs:workload:gpu_usage{cluster=\"$cluster\", namespace=~\"$namespace\", profile=\"$profile\"}))[$days:]) / max_over_time((sum by (workload, namespace) (acm_rs:workload:gpu_request{cluster=\"$cluster\", namespace=~\"$namespace\", profile=\"$profile\"}))[$days:])"
    },
    {
     "expr": "max_over_time((sum by (workload, namespace) (acm_rs:workload:gpu_usage{cluster=\"$cluster\", namespace=~\"$namespace\", profile=\"$profile\"}))[$days:])"
    },
    {
     "expr": "max_over_time((sum by (workload, namespace) (acm_rs:workload:gpu_request{cluster=\"$cluster\", namespace=~\"$namespace\", profile=\"$profile\"}))[$days:])"
    },
    {
     "expr": "max_over_time((sum by (workload, namespace) (acm_rs:workload:gpu_recommendation{cluster=\"$cluster\", namespace=~\"$namespace\", profile=\"$profile\"}))[$days:])"
    },
    {
     "expr": "max_over_time((sum by (workload, namespace) (acm_rs:workload:gpu_memory_used{cluster=\"$cluster\", namespace=~\"$namespace\", profile=\"$profile\"}))[$days:])"
    },
    {
     "expr": "max_over_time((sum by (workload, namespace) (acm_rs:workload:gpu_memory_total{cluster=\"$cluster\", namespace=~\"$namespace\", profile=\"$profile\"}))[$days:])"
    },
    {
     "expr": "max_over_time((sum by (workload, namespace) (acm_rs:workload:gpu_memory_recommendation{cluster=\"$cluster\", namespace=~\"$namespace\", profile=\"$profile\"}))[$days:])"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Pod GPU Quota",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "max_over_time((sum by (pod, namespace, workload, workload_type) (acm_rs:pod:gpu_usage{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:]) / max_over_time((sum by (pod, namespace, workload, workload_type) (acm_rs:pod:gpu_request{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:])"
    },
    {
     "expr": "max_over_time((sum by (pod, namespace, workload, workload_type) (acm_rs:pod:gpu_usage{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:])"
    },
    {
     "expr": "max_over_time((sum by (pod, namespace, workload, workload_type) (acm_rs:pod:gpu_request{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:])"
    },
    {
     "expr": "max_over_time((sum by (pod, namespace, workload, workload_type) (acm_rs:pod:gpu_recommendation{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:])"
    },
    {
     "expr": "max_over_time((sum by (pod, namespace, workload, workload_type) (acm_rs:pod:gpu_memory_used{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:])"
    },
    {
     "expr": "max_over_time((sum by (pod, namespace, workload, workload_type) (acm_rs:pod:gpu_memory_total{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:])"
    },
    {
     "expr": "max_over_time((sum by (pod, namespace, workload, workload_type) (acm_rs:pod:gpu_memory_recommendation{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:])"
    }
   ]
  }
 ]
}