{
 "title": "ACM Right-Sizing Workloads & Pods",
 "tags": [
  "ACM",
  "Right-Sizing"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values({__name__=~\"acm_rs:workload:(cpu_request|cpu_usage|memory_request|memory_usage)\"},cluster)"
    }
   },
   {
    "name": "profile",
    "label": "Profile",
    "query": {
     "query": "label_values({__name__=~\"acm_rs:workload:(cpu_request|cpu_usage|memory_request|memory_usage)\",cluster=\"$cluster\"},profile)"
    }
   },
   { "name": "days", "label": "Aggregation", "query": "1d, 2d, 5d, 10d, 30d, 60d, 90d" },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values({__name__=~\"acm_rs:workload:(cpu_usage|cpu_request)\",cluster=\"$cluster\",profile=\"$profile\"},namespace)"
    }
   },
   {
    "name": "workload_type",
    "label": "Workload Type",
    "query": "Deployment,StatefulSet,DaemonSet,ReplicaSet,Job,CronJob"
   },
   {
    "name": "workload",
    "label": "Workload",
    "query": {
     "query": "label_values(acm_rs:workload:cpu_usage{cluster=\"$cluster\",namespace=~\"$namespace\",workload_type=~\"$workload_type\",profile=\"$profile\"},workload)"
    }
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilization of Top Workloads",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(20,\nsum by (workload, namespace) (acm_rs:workload:cpu_usage{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", profile=\"$profile\"})\n/\nclamp_min(sum by (workload, namespace) (acm_rs:workload:cpu_request{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", profile=\"$profile\"}), 1e-9)\n)",
     "legendFormat": "{{workload}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Workload CPU Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(\n  (sum by (workload, namespace, workload_type) (acm_rs:workload:cpu_usage{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", profile=\"$profile\"}))[$days:]\n)\n/\nclamp_min(\n  max_over_time(\n    (sum by (workload, namespace, workload_type) (acm_rs:workload:cpu_request{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", profile=\"$profile\"}))[$days:]\n  )\n, 1e-9)"
    },
    {
     "expr": "max_over_time(\n  (sum by (workload, namespace, workload_type) (acm_rs:workload:cpu_usage{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", profile=\"$profile\"}))[$days:]\n)"
    },
    {
     "expr": "max_over_time(\n  (sum by (workload, namespace, workload_type) (acm_rs:workload:cpu_request{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", profile=\"$profile\"}))[$days:]\n)"
    },
    {
     "expr": "max_over_time(\n  (sum by (workload, namespace, workload_type) (acm_rs:workload:cpu_limit{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", profile=\"$profile\"}))[$days:]\n)"
    },
    {
     "expr": "max_over_time(\n  (sum by (workload, namespace, workload_type) (acm_rs:workload:cpu_recommendation{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", profile=\"$profile\"}))[$days:]\n)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Memory Utilization of Top Workloads",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "topk(20,\nsum by (workload, namespace) (acm_rs:workload:memory_usage{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", profile=\"$profile\"})\n/\nclamp_min(sum by (workload, namespace) (acm_rs:workload:memory_request{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", profile=\"$profile\"}), 1e-9)\n)",
     "legendFormat": "{{workload}} ({{namespace}})"
    }
   ]
  },
  {
   "title": "Workload Memory Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(\n  (sum by (workload, namespace, workload_type) (acm_rs:workload:memory_usage{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", profile=\"$profile\"}))[$days:]\n)\n/\nclamp_min(\n  max_over_time(\n    (sum by (workload, namespace, workload_type) (acm_rs:workload:memory_request{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", profile=\"$profile\"}))[$days:]\n  )\n, 1e-9)"
    },
    {
     "expr": "max_over_time(\n  (sum by (workload, namespace, workload_type) (acm_rs:workload:memory_usage{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", profile=\"$profile\"}))[$days:]\n)"
    },
    {
     "expr": "max_over_time(\n  (sum by (workload, namespace, workload_type) (acm_rs:workload:memory_request{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", profile=\"$profile\"}))[$days:]\n)"
    },
    {
     "expr": "max_over_time(\n  (sum by (workload, namespace, workload_type) (acm_rs:workload:memory_limit{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", profile=\"$profile\"}))[$days:]\n)"
    },
    {
     "expr": "max_over_time(\n  (sum by (workload, namespace, workload_type) (acm_rs:workload:memory_recommendation{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", profile=\"$profile\"}))[$days:]\n)"
    }
   ]
  },
  { "title": "Pods", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Pod CPU Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max_over_time(\n  (sum by (pod, namespace, workload, workload_type) (acm_rs:pod:cpu_usage{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:]\n)\n/\nclamp_min(\n  max_over_time(\n    (sum by (pod, namespace, workload, workload_type) (acm_rs:pod:cpu_request{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:]\n  )\n, 1e-9)"
    },
    {
     "expr": "max_over_time(\n  (sum by (pod, namespace, workload, workload_type) (acm_rs:pod:cpu_usage{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:]\n)"
    },
    {
     "expr": "max_over_time(\n  (sum by (pod, namespace, workload, workload_type) (acm_rs:pod:cpu_request{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:]\n)"
    },
    {
     "expr": "max_over_time(\n  (sum by (pod, namespace, workload, workload_type) (acm_rs:pod:cpu_limit{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:]\n)"
    },
    {
     "expr": "max_over_time(\n  (sum by (pod, namespace, workload, workload_type) (acm_rs:pod:cpu_recommendation{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:]\n)"
    }
   ]
  },
  {
   "title": "Pod Memory Table",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max_over_time(\n  (sum by (pod, namespace, workload, workload_type) (acm_rs:pod:memory_usage{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:]\n)\n/\nclamp_min(\n  max_over_time(\n    (sum by (pod, namespace, workload, workload_type) (acm_rs:pod:memory_request{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:]\n  )\n, 1e-9)"
    },
    {
     "expr": "max_over_time(\n  (sum by (pod, namespace, workload, workload_type) (acm_rs:pod:memory_usage{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:]\n)"
    },
    {
     "expr": "max_over_time(\n  (sum by (pod, namespace, workload, workload_type) (acm_rs:pod:memory_request{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:]\n)"
    },
    {
     "expr": "max_over_time(\n  (sum by (pod, namespace, workload, workload_type) (acm_rs:pod:memory_limit{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:]\n)"
    },
    {
     "expr": "max_over_time(\n  (sum by (pod, namespace, workload, workload_type) (acm_rs:pod:memory_recommendation{cluster=\"$cluster\", namespace=~\"$namespace\", workload_type=~\"$workload_type\", workload=~\"$workload\", profile=\"$profile\"}))[$days:]\n)"
    }
   ]
  }
 ]
}