apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  labels:
    app.kubernetes.io/component: platform-metrics-collector
    app.kubernetes.io/part-of: multicluster-observability-addon
    app.kubernetes.io/managed-by: multicluster-observability-operator
  name: platform-metrics-analytics
  namespace: open-cluster-management-observability
spec:
  jobName: platform-metrics
  metricsPath: /federate
  params:
    match[]:
    - '{__name__="acm_rs:namespace:cpu_request_hard"}'
    - '{__name__="acm_rs:namespace:cpu_request"}'
    - '{__name__="acm_rs:namespace:cpu_usage"}'
    - '{__name__="acm_rs:namespace:cpu_recommendation"}'
    - '{__name__="acm_rs:namespace:memory_request_hard"}'
    - '{__name__="acm_rs:namespace:memory_request"}'
    - '{__name__="acm_rs:namespace:memory_usage"}'
    - '{__name__="acm_rs:namespace:memory_recommendation"}'
    - '{__name__="acm_rs:cluster:cpu_request"}'
    - '{__name__="acm_rs:cluster:cpu_usage"}'
    - '{__name__="acm_rs:cluster:cpu_recommendation"}'
    - '{__name__="acm_rs:cluster:memory_request"}'
    - '{__name__="acm_rs:cluster:memory_usage"}'
    - '{__name__="acm_rs:cluster:memory_recommendation"}'
  metricRelabelings:
  - action: labeldrop
    regex: prometheus_replica|managed_cluster|id
  scrapeClass: ocp-monitoring
  scheme: HTTPS
  staticConfigs:
  - targets:
    - prometheus-k8s.openshift-monitoring.svc:9091
