apiVersion: monitoring.rhobs/v1alpha1
kind: ScrapeConfig
metadata:
  labels:
    app.kubernetes.io/component: platform-metrics-collector
    app.kubernetes.io/part-of: multicluster-observability-addon
    app.kubernetes.io/managed-by: multicluster-observability-operator
  name: platform-metrics-right-sizing
  namespace: open-cluster-management-observability
spec:
  jobName: right-sizing
  metricsPath: /federate
  params:
    match[]:
    - '{__name__="acm_rs:namespace:cpu_request_hard"}'
    - '{__name__="acm_rs:namespace:cpu_request"}'
    - '{__name__="acm_rs:namespace:cpu_usage"}'
    - '{__name__="acm_rs:namespace:cpu_recommendation"}'
    - '{__name__="acm_rs:namespace:memory_request_hard"}'
    - '{__name__="acm_rs:namespace:memory_request"}'
    - '{__name__="acm_rs:namespace:memory_usage"}'
    - '{__name__="acm_rs:namespace:memory_recommendation"}'
    - '{__name__="acm_rs:cluster:cpu_request"}'
    - '{__name__="acm_rs:cluster:cpu_usage"}'
    - '{__name__="acm_rs:cluster:cpu_recommendation"}'
    - '{__name__="acm_rs:cluster:memory_request"}'
    - '{__name__="acm_rs:cluster:memory_usage"}'
    - '{__name__="acm_rs:cluster:memory_recommendation"}'
    - '{__name__="acm_rs:namespace:gpu_request"}'
    - '{__name__="acm_rs:namespace:gpu_usage"}'
    - '{__name__="acm_rs:namespace:gpu_recommendation"}'
    - '{__name__="acm_rs:namespace:gpu_memory_used"}'
    - '{__name__="acm_rs:namespace:gpu_memory_recommendation"}'
    - '{__name__="acm_rs:namespace:gpu_memory_total"}'
    - '{__name__="acm_rs:namespace:gpu_power_usage_watts"}'
    - '{__name__="acm_rs:namespace:gpu_temperature_celsius"}'
    - '{__name__="acm_rs:namespace:gpu_sm_clock_hertz"}'
    - '{__name__="acm_rs:namespace:gpu_memory_clock_hertz"}'
    - '{__name__="acm_rs:pod:cpu_request"}'
    - '{__name__="acm_rs:pod:cpu_limit"}'
    - '{__name__="acm_rs:pod:cpu_usage"}'
    - '{__name__="acm_rs:pod:cpu_recommendation"}'
    - '{__name__="acm_rs:pod:memory_request"}'
    - '{__name__="acm_rs:pod:memory_limit"}'
    - '{__name__="acm_rs:pod:memory_usage"}'
    - '{__name__="acm_rs:pod:memory_recommendation"}'
    - '{__name__="acm_rs:pod:gpu_request"}'
    - '{__name__="acm_rs:pod:gpu_usage"}'
    - '{__name__="acm_rs:pod:gpu_recommendation"}'
    - '{__name__="acm_rs:pod:gpu_memory_used"}'
    - '{__name__="acm_rs:pod:gpu_memory_recommendation"}'
    - '{__name__="acm_rs:pod:gpu_memory_total"}'
    - '{__name__="acm_rs:workload:cpu_request"}'
    - '{__name__="acm_rs:workload:cpu_limit"}'
    - '{__name__="acm_rs:workload:cpu_usage"}'
    - '{__name__="acm_rs:workload:cpu_recommendation"}'
    - '{__name__="acm_rs:workload:memory_request"}'
    - '{__name__="acm_rs:workload:memory_limit"}'
    - '{__name__="acm_rs:workload:memory_usage"}'
    - '{__name__="acm_rs:workload:memory_recommendation"}'
    - '{__name__="acm_rs:workload:gpu_request"}'
    - '{__name__="acm_rs:workload:gpu_usage"}'
    - '{__name__="acm_rs:workload:gpu_recommendation"}'
    - '{__name__="acm_rs:workload:gpu_memory_used"}'
    - '{__name__="acm_rs:workload:gpu_memory_recommendation"}'
    - '{__name__="acm_rs:workload:gpu_memory_total"}'
    - '{__name__="acm_rs:cluster:gpu_request"}'
    - '{__name__="acm_rs:cluster:gpu_usage"}'
    - '{__name__="acm_rs:cluster:gpu_recommendation"}'
    - '{__name__="acm_rs:cluster:gpu_memory_used"}'
    - '{__name__="acm_rs:cluster:gpu_memory_recommendation"}'
    - '{__name__="acm_rs:cluster:gpu_memory_total"}'
    - '{__name__="acm_rs:namespace:gpu_type"}'
    - '{__name__="acm_rs_vm:namespace:cpu_request"}'
    - '{__name__="acm_rs_vm:namespace:cpu_usage"}'
    - '{__name__="acm_rs_vm:namespace:cpu_recommendation"}'
    - '{__name__="acm_rs_vm:namespace:memory_request"}'
    - '{__name__="acm_rs_vm:namespace:memory_usage"}'
    - '{__name__="acm_rs_vm:namespace:memory_recommendation"}'
    - '{__name__="kubevirt_vm_running_status_last_transition_timestamp_seconds"}'
  metricRelabelings:
  - action: labeldrop
    regex: managed_cluster|id
