version: "2"

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # TODO(saswatamcode): Remove this by cleaning up our test suite.
  tests: false


linters:
  default: none
  enable:
    - bodyclose
    - contextcheck
    - dupword
    - embeddedstructfieldcheck
    - errcheck
    - errorlint
    - exptostd
    - gocognit
    - goconst
    - gocritic
    - gosec
    - govet
    - ineffassign
    - intrange
    - loggercheck
    - misspell
    - modernize
    - nilerr
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace

  settings:
    errcheck:
      exclude-functions:
        - (github.com/go-kit/log.Logger).Log
    gocognit:
      min-complexity: 50
    goconst:
      min-occurrences: 5
      ignore-string-values:
        - 'true'
    gosec:
      excludes:
        - G104 # Already covererd by errcheck which allows exclusions
    misspell:
      locale: US
    revive:
      enable-default-rules: true
      rules:
        - name: var-naming
          disabled: true
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true

  exclusions:
    rules:
      - path: tests/
        linters:
          - gocognit
          - gosec
          - revive

formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines

  settings:
    golines:
      # Target maximum line length.
      # Default: 100
      max-len: 200

  exclusions:
    paths:
      - "vendor/.*"
      - "zz_generated.deepcopy.go"

