# This file contains all available configuration options
# with their default values.

# options for analysis running
run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 5m

  # exit code when at least one issue was found, default is 1
  issues-exit-code: 1

  # TODO(saswatamcode): Remove this by cleaning up our test suite.
  tests: false

# output configuration options
output:
  # colored-line-number|line-number|json|tab|checkstyle, default is "colored-line-number"
  formats:
    - format: colored-line-number

  # print lines of code with issue, default is true
  print-issued-lines: true

  # print linter name in the end of issue text, default is true
  print-linter-name: true

linters:
  enable:
    # Sorted alphabetically.
    - bodyclose
    - errcheck
    - exptostd
    - goconst
    - gocritic
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - intrange
    - loggercheck
    - misspell
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - staticcheck
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace

linters-settings:
  errcheck:
    exclude-functions:
      - (github.com/go-kit/log.Logger).Log
  misspell:
    locale: US
  goconst:
    min-occurrences: 5

issues:
  exclude-rules:
    # We don't check metrics naming in the tests.
    - path: _test\.go
      linters:
      - promlinter
