# Command to build this Dockerfile
# docker build -f Dockerfile -t quay.io/vboulos/acmqe-automation/obs:obs-ginkgo_1_14_2-linux-go .

FROM quay.io/vboulos/acmqe-automation/ginkgo_1_14_2-linux-go

# Copy the GRC repo repo into /tmp/grc folder
RUN mkdir /tmp/obs
WORKDIR /tmp/obs
COPY . .

# good colors for most applications
ENV TERM=xterm

CMD ["/bin/bash"]