FROM quay.io/vboulos/acmqe-automation/go:go1.21-ginkgo2.17.1

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN <<'EOF'
set -exo pipefail
shopt -s inherit_errexit

mkdir -p /tmp/obs /go ~/.kube /alabama/.kube

chgrp -R 0 /tmp
chmod -R g=u /tmp

chgrp -R 0 /go
chmod -R g=u /go

chgrp -R 0 ~/.kube
chmod -R g=u ~/.kube

chgrp -R 0 /alabama/.kube
chmod -R g=u /alabama/.kube
EOF

ENV TERM=xterm

WORKDIR /tmp/obs
COPY . .

CMD ["/bin/bash"]
