# Copyright Contributors to the Open Cluster Management project

-include /opt/build-harness/Makefile.prow

.PHONY: build
build:
	go build -o bin/manager main.go

unit-tests:
	go mod vendor
	go test `go list ./... | grep -v test`

e2e-tests:
	@./cicd-scripts/run-e2e-tests.sh
