# Copyright Contributors to the Open Cluster Management project

-include /opt/build-harness/Makefile.prow

.PHONY: build
build:
	go build -o manager ./cmd/manager

unit-tests:
	go test `go list ./... | grep -v test`
