module _ // Auto generated by https://github.com/bwplotka/bingo. DO NOT EDIT

go 1.23.0

replace golang.org/x/tools => golang.org/x/tools v0.33.0

require github.com/operator-framework/operator-sdk v1.34.2 // cmd/operator-sdk
