# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/observability.open-cluster-management.io_multiclusterobservabilities.yaml
- bases/observability.open-cluster-management.io_observabilityaddons.yaml
- bases/core.observatorium.io_observatoria.yaml
# +kubebuilder:scaffold:crdkustomizeresource

# patches here are for enabling webhook with ocp service serving certificate.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: patches/webhook_multiclusterobservabilities_cainjection_patch.yaml
