{
 "title": "ACM - Clusters Overview",
 "tags": [ "ACM" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(node_cpu_seconds_total, cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Control Plane Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Server",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.99,sum(rate(apiserver_request_duration_seconds_bucket{job=\"apiserver\", verb!=\"WATCH\"}[5m])) by (verb,le,cluster))) by (cluster)"
    },
    {
     "expr": "(sum(up{job=\"apiserver\"} == 1) by (cluster) / count(up{job=\"apiserver\"}) by (cluster))"
    },
    {
     "expr": "sum by (cluster)(rate(apiserver_request_total{code=~\"5..\"}[1h]))"
    }
   ]
  },
  { "title": "Optimization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU",
   "type": "table",
   "description": "Highlights % differences between CPU requests commitments vs utilization.  When this difference is large ( >20%), it means that resources are reserved but unused.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_cpu_cores) by (cluster) / sum(kube_node_status_allocatable_cpu_cores) by (cluster)) - (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])) by (cluster))"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (cluster) / sum(kube_node_status_allocatable_cpu_cores) by (cluster)"
    },
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])) by (cluster)"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "table",
   "description": "Highlights % differences between Memory requests commitments vs utilization.  When this difference is large ( >20%), it means that resources are reserved but unused.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum(kube_pod_container_resource_requests_memory_bytes) by (cluster) / sum(kube_node_status_allocatable_memory_bytes) by (cluster))\n-\n(1 - sum(:node_memory_MemAvailable_bytes:sum) by (cluster) / sum(kube_node_status_allocatable_memory_bytes) by (cluster))"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (cluster) / sum(kube_node_status_allocatable_memory_bytes) by (cluster)"
    },
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum) by (cluster) / sum(kube_node_status_allocatable_memory_bytes) by (cluster)"
    }
   ]
  },
  { "title": "Capacity / Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum) by (cluster)"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores) by (cluster)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) by (cluster) / sum(kube_node_status_allocatable_cpu_cores) by (cluster)"
    },
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])) by (cluster)"
    }
   ]
  },
  {
   "title": "Top 5 Utilized Clusters (% CPU usage)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(5, (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[$__interval])) by (cluster)))"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum) by (cluster)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (cluster) / sum(kube_node_status_allocatable_memory_bytes) by (cluster)"
    },
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum) by (cluster) / sum(kube_node_status_allocatable_memory_bytes) by (cluster)"
    }
   ]
  },
  {
   "title": "Top 5 Utilized Clusters (% Memory usage)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "topk(5, (1 - sum(:node_memory_MemAvailable_bytes:sum) by (cluster) / sum(kube_node_status_allocatable_memory_bytes) by (cluster)))",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes) by (cluster)"
    },
    {
     "expr": "sum(node_filesystem_avail_bytes) by (cluster)"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes) by (cluster) - sum(node_filesystem_avail_bytes) by (cluster)) / sum(node_filesystem_size_bytes) by (cluster)"
    }
   ]
  },
  {
   "title": "Top 5 Utilized Clusters (Disk)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes) by (cluster) - sum(node_filesystem_avail_bytes) by (cluster)) / sum(node_filesystem_size_bytes) by (cluster) * 100",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}