{
 "title": "ACM - Clusters Overview",
 "tags": [ "ACM" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(node_cpu_seconds_total, cluster)"
   }
  ]
 },
 "panels": [
  { "title": "Control Plane Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Control Plane",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(sum(up{job=\"apiserver\"} == 1) by (cluster) / count(up{job=\"apiserver\"}) by (cluster))"
    },
    {
     "expr": "sum by (cluster)(rate(apiserver_request_count{code=~\"5..\"}[1h]))"
    },
    {
     "expr": "max (rate(apiserver_request_latencies_summary_sum{verb!=\"WATCH\"}[1h])) by (cluster)  / \nmax (rate(apiserver_request_latencies_summary_count{verb!=\"WATCH\"}[1h])) by (cluster)"
    },
    {
     "expr": "(sum(up{job=\"kube-controller-manager\"} == 1) by (cluster) / count(up{job=\"kube-controller-manager\"}) by (cluster))"
    },
    {
     "expr": "(sum(up{job=\"scheduler\"} == 1) by (cluster) / count(up{job=\"scheduler\"}) by (cluster))"
    }
   ]
  },
  { "title": "Optimization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "${cluster}",
   "type": "stat",
   "description": "Highlights % differences between CPU/Memory requests commitments vs utilization.  When this difference is large, it means that resources are reserved but unused.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "repeat": "cluster",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=~\"$cluster\"}) / sum(kube_node_status_allocatable_cpu_cores{cluster=~\"$cluster\"})"
    },
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\",cluster=\"$cluster\"}[$__interval]))"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})"
    },
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  { "title": "Cluster Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Managed Clusters",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count( count by (cluster) (cluster_version + 0 + 0))"
    }
   ]
  },
  {
   "title": "Total Cores",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum)"
    }
   ]
  },
  {
   "title": "Cluster Resources I",
   "type": "table",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 16 },
   "targets": [
    {
     "expr": "sum(cluster:usage:resources:sum{resource=~\"namespaces\"}) by (cluster)"
    },
    {
     "expr": "sum(cluster:usage:resources:sum{resource=~\"pods\"}) by (cluster)"
    },
    {
     "expr": "sum(cluster:usage:resources:sum{resource=~\"routes.route.openshift.io\"}) by (cluster)"
    },
    {
     "expr": "sum(cluster_infrastructure_provider) by (cluster, type)"
    },
    {
     "expr": "sum(cluster_version_payload) by (cluster, version)"
    }
   ]
  },
  {
   "title": "Cloud Providers",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(cluster_infrastructure_provider) by (type)",
     "legendFormat": "Cloud Providers"
    }
   ]
  },
  {
   "title": "OCP versions",
   "type": "bargauge",
   "description": "OCP versions across managed clusters",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(cluster_version_payload{type=\"applied\"}) by (version)"
    }
   ]
  },
  {
   "title": "Cluster Resources II",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum) by (cluster)"
    },
    {
     "expr": "sum(cluster:cpu_usage_cores:sum) by (cluster)"
    },
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum) by (cluster)"
    },
    {
     "expr": "sum(cluster:memory_usage_bytes:sum) by (cluster)"
    },
    {
     "expr": "sum(node_filesystem_size_bytes) by (cluster)"
    },
    {
     "expr": "sum(node_filesystem_size_bytes) by (cluster) - sum(node_filesystem_avail_bytes) by (cluster)"
    }
   ]
  },
  { "title": "Capacity / Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "CPU",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum) by (cluster)"
    },
    {
     "expr": "sum(cluster:container_cpu_usage:ratio) by (cluster)"
    },
    {
     "expr": "sum(cluster:container_spec_cpu_shares:ratio) by (cluster)"
    }
   ]
  },
  {
   "title": "Top 5 Utilized Clusters (% CPU usage)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, cluster:container_cpu_usage:ratio * 100)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "targets": [
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum / 1000000000) by (cluster)"
    },
    {
     "expr": "sum(cluster:memory_usage:ratio) by (cluster)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (cluster) / sum(kube_node_status_allocatable_memory_bytes) by (cluster)"
    }
   ]
  },
  {
   "title": "Top 5 Utilized Clusters (% Memory usage)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "topk(5, cluster:memory_usage:ratio * 100)",
     "legendFormat": "{{cluster}}"
    }
   ]
  },
  {
   "title": "Filesystem",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes) by (cluster)"
    },
    {
     "expr": "sum(node_filesystem_avail_bytes) by (cluster)"
    },
    {
     "expr": "(sum(node_filesystem_size_bytes) by (cluster) - sum(node_filesystem_avail_bytes) by (cluster)) / sum(node_filesystem_size_bytes) by (cluster)"
    }
   ]
  },
  {
   "title": "Top 5 Utilized Clusters (Disk)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(node_filesystem_size_bytes) by (cluster) - sum(node_filesystem_avail_bytes) by (cluster)) / sum(node_filesystem_size_bytes) by (cluster) * 100",
     "legendFormat": "{{cluster}}"
    }
   ]
  }
 ]
}
{
 "title": "ACM - Cluster Optimization Overview",
 "tags": [ "ACM" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(node_cpu_seconds_total,cluster)"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - avg(rate(node_cpu_seconds_total{mode=\"idle\", cluster=\"$cluster\"}[$__interval]))"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_cpu_cores{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Quota",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "count(mixin_pod_workload{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "count(avg(mixin_pod_workload{cluster=\"$cluster\"}) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\"}) by (namespace) / sum(kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{cluster=\"$cluster\"}) by (namespace) / sum(kube_pod_container_resource_limits_cpu_cores{cluster=\"$cluster\"}) by (namespace)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Memory Utilisation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "1 - sum(:node_memory_MemAvailable_bytes:sum{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 20, "x": 4, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!=\"\"}) by (namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Memory Requests Commitment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Memory Limits Commitment",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\"}) / sum(kube_node_status_allocatable_memory_bytes{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Requests by Namespace",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "count(mixin_pod_workload{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "count(avg(mixin_pod_workload{cluster=\"$cluster\"}) by (workload, namespace)) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!=\"\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_requests_memory_bytes{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\"}) by (namespace)"
    },
    {
     "expr": "sum(container_memory_rss{cluster=\"$cluster\", container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_limits_memory_bytes{cluster=\"$cluster\"}) by (namespace)"
    }
   ]
  }
 ]
}