{
 "title": "ACM: Clusters Monitoring",
 "description": "Monitors managed cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "ACM" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Cluster Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Managed Clusters",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count by (cluster) (cluster_version + 0 + 0))"
    }
   ]
  },
  {
   "title": "Total CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "first",
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum)"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum)"
    }
   ]
  },
  {
   "title": "OCP Version Across Clusters",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count(cluster_version_payload{type=\"applied\"}) by (version)"
    }
   ]
  },
  {
   "title": "Cloud Provider Across Clusters",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "count(cluster_infrastructure_provider) by (type)"
    }
   ]
  },
  {
   "title": "Clusters with Nodes in High Res Commit",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count ((sum (kube_pod_container_resource_requests_memory_bytes) by (cluster, node) / sum (machine_memory_bytes) by (cluster, node) > 0.8) or (sum (kube_pod_container_resource_requests_cpu_cores) by (cluster, node) / sum (machine_cpu_cores) by (cluster, node) > 0.8)) by (cluster)"
    }
   ]
  },
  {
   "title": "Cluster Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(cluster:usage:resources:sum{resource=~\"namespaces\"}) by (cluster)"
    },
    {
     "expr": "sum(cluster:usage:resources:sum{resource=~\"pods\"}) by (cluster)"
    },
    {
     "expr": "sum(cluster:usage:resources:sum{resource=~\"routes.route.openshift.io\"}) by (cluster)"
    },
    {
     "expr": "sum(cluster:cpu_usage_cores:sum) by (cluster)"
    },
    {
     "expr": "sum(cluster:memory_usage_bytes:sum) by (cluster)"
    },
    {
     "expr": "sum(cluster_infrastructure_provider) by (cluster, type)"
    },
    {
     "expr": "sum(cluster_version_payload) by (cluster, version)"
    }
   ]
  },
  { "title": "Capacity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "CPU Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(cluster:capacity_cpu_cores:sum) by (cluster)"
    },
    {
     "expr": "sum(cluster:container_cpu_usage:ratio) by (cluster)"
    },
    {
     "expr": "sum(cluster:container_spec_cpu_shares:ratio) by (cluster)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 22 },
   "targets": [
    {
     "expr": "sum(cluster:capacity_memory_bytes:sum) by (cluster)"
    },
    {
     "expr": "sum(cluster:memory_usage:ratio) by (cluster)"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) by (cluster) / sum(kube_node_status_allocatable_memory_bytes) by (cluster)"
    }
   ]
  },
  {
   "title": "Route Connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(rate(haproxy_backend_connections_total[5m])) by (cluster)"
    }
   ]
  },
  { "title": "Compliance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Workload Compliance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ]
  },
  {
   "title": "Security Compliance",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 39 },
   "content": "\n# Security policy compliance across Clusters\n\nFor more details: [GRC Console](https://multicloud-console.apps.trusty-toad.dev05.red-chesterfield.com/multicloud/policies/all)\n\n\n\n"
  }
 ]
}