apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: etcd-hcp-user-workload-metrics-collector # Expected label by MCOA for HCPs
    app.kubernetes.io/part-of: multicluster-observability-addon
    app.kubernetes.io/managed-by: multicluster-observability-operator
  name: etcd-hcp-uwl-rules-default
  namespace: open-cluster-management-observability
spec:
  groups:
  - name: acm-etcd-hcp-uwl-rules-default
    rules:
    - expr: sum(grpc_server_started_total{job="etcd",grpc_service="etcdserverpb.Lease",grpc_type="bidi_stream",clusterID!=""}) by (cluster, clusterID, managementcluster, managementclusterID)
        - sum(grpc_server_handled_total{job="etcd",grpc_service="etcdserverpb.Lease",grpc_type="bidi_stream",clusterID!=""}) by (cluster, clusterID, managementcluster, managementclusterID)
      record: active_streams_lease:grpc_server_handled_total:sum
    - expr: sum(grpc_server_started_total{job="etcd",grpc_service="etcdserverpb.Watch",grpc_type="bidi_stream",clusterID!=""}) by (cluster, clusterID, managementcluster, managementclusterID)
        - sum(grpc_server_handled_total{job="etcd",grpc_service="etcdserverpb.Watch",grpc_type="bidi_stream",clusterID!=""})  by (cluster, clusterID, managementcluster, managementclusterID)
      record: active_streams_watch:grpc_server_handled_total:sum
    - expr: sum(rate(grpc_server_started_total{job="etcd",grpc_type="unary",clusterID!=""}[5m])) by (cluster, clusterID, managementcluster, managementclusterID)
      record: grpc_server_started_total:etcd_unary:sum_rate
    - expr: sum(rate(grpc_server_handled_total{job="etcd",grpc_type="unary",grpc_code!="OK",clusterID!=""}[5m])) by (cluster, clusterID, managementcluster, managementclusterID)
      record: rpc_rate:grpc_server_handled_total:sum_rate
