apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: etcd-hcp-user-workload-metrics-collector # Expected label by MCOA for HCPs
    app.kubernetes.io/part-of: multicluster-observability-addon
    app.kubernetes.io/managed-by: multicluster-observability-operator
  name: etcd-hcp-uwl-metrics-default
  namespace: open-cluster-management-observability
spec:
  jobName: etcd-hcp-uwl-metrics-default
  metricsPath: /federate
  params:
    match[]:
    - '{__name__="active_streams_lease:grpc_server_handled_total:sum"}'
    - '{__name__="active_streams_watch:grpc_server_handled_total:sum"}'
    - '{__name__="etcd_mvcc_db_total_size_in_bytes"}'
    - '{__name__="etcd_disk_backend_commit_duration_seconds_bucket"}'
    - '{__name__="etcd_disk_wal_fsync_duration_seconds_bucket"}'
    - '{__name__="etcd_network_client_grpc_received_bytes_total"}'
    - '{__name__="etcd_network_client_grpc_sent_bytes_total"}'
    - '{__name__="etcd_network_peer_received_bytes_total"}'
    - '{__name__="etcd_network_peer_sent_bytes_total"}'
    - '{__name__="etcd_server_has_leader"}'
    - '{__name__="etcd_server_leader_changes_seen_total"}'
    - '{__name__="etcd_server_proposals_applied_total"}'
    - '{__name__="etcd_server_proposals_committed_total"}'
    - '{__name__="etcd_server_proposals_failed_total"}'
    - '{__name__="etcd_server_proposals_pending"}'
    - '{__name__="grpc_server_started_total:etcd_unary:sum_rate"}'
    - '{__name__="process_resident_memory_bytes",job="etcd"}'
    - '{__name__="rpc_rate:grpc_server_handled_total:sum_rate"}'
  metricRelabelings:
  - action: labeldrop
    regex: prometheus_replica|managed_cluster|id
  scrapeClass: ocp-monitoring
  scheme: HTTPS
  staticConfigs:
  - targets:
    - prometheus-user-workload.openshift-user-workload-monitoring.svc:9092


