resources:
- dash-acm-clusters-overview-ocp311.yaml
- dash-acm-optimization-overview-ocp311.yaml
- dash-k8s-capacity-planning-ocp311.yaml
- dash-k8s-compute-resources-namespace-pods-ocp311.yaml
- dash-k8s-compute-resources-pod-ocp311.yaml
- dash-k8s-namespaces-in-cluster-ocp311.yaml
- dash-k8s-pods-in-namespace-ocp311.yaml
- dash-k8s-summary-by-node-ocp311.yaml
