{
 "title": "ACM: Spoke Cluster Monitoring",
 "description": "Monitors managed cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "ACM" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Cluster Resources",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(cluster:usage:resources:sum{resource=~\"namespaces\"}) by (cluster)"
    },
    {
     "expr": "sum(cluster:usage:resources:sum{resource=~\"pods\"}) by (cluster)"
    }
   ]
  },
  {
   "title": "Clusters CPU Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(cluster:cpu_usage_cores:sum) by (cluster)"
    },
    {
     "expr": "sum(cluster:container_cpu_usage:ratio) by (cluster)"
    },
    {
     "expr": "sum(cluster:container_spec_cpu_shares:ratio) by (cluster)"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(cluster:memory_usage_bytes:sum) by (cluster)"
    },
    {
     "expr": "sum(cluster:memory_usage:ratio) by (cluster)"
    }
   ]
  }
 ]
}