apiVersion: observability.open-cluster-management.io/v1beta2
kind: MultiClusterObservability
metadata:
  name: observability
spec:
  advanced:
    retentionConfig:
      retentionResolution1h: 30d
      retentionResolution5m: 14d
      retentionResolutionRaw: 5d
  enableDownsampling: false
  imagePullPolicy: IfNotPresent
  imagePullSecret: multiclusterhub-operator-pull-secret
  nodeSelector:
    kubernetes.io/os: linux
  observabilityAddonSpec:
    enableMetrics: true
    interval: 300
    scrapeSizeLimitBytes: 1073741824
  storageConfig:
    alertmanagerStorageSize: 2Gi
    compactStorageSize: 2Gi
    metricObjectStorage:
      key: thanos.yaml
      name: thanos-object-storage
    receiveStorageSize: 2Gi
    ruleStorageSize: 2Gi
    storageClass: gp2
    storeStorageSize: 2Gi
