apiVersion: v1
data: {}
kind: Secret
metadata:
    name: alertmanager-kube-rbac-proxy-web
stringData:
  config.yaml: |-
    "authorization":
      "resourceAttributes":
        "apiGroup": "monitoring.coreos.com"
        "name": "observability"
        "namespace": "open-cluster-management-observability"
        "resource": "alertmanagers"
        "subresource": "api"
type: Opaque