apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: observability
  name: alertmanager
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: alertmanager-tls
spec:
  ports:
  - name: oauth-proxy
    port: 9095
    protocol: TCP
    targetPort: oauth-proxy
  selector:
    alertmanager: observability
    app: multicluster-observability-alertmanager
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  type: ClusterIP
