apiVersion: v1
kind: Service
metadata:
  labels:
    alertmanager: observability
  name: alertmanager
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: alertmanager-tls
spec:
  ports:
  - name: web
    port: 9095
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: observability
    app: multicluster-observability-alertmanager
  type: ClusterIP
  clusterIP: None
