{
 "title": "ACM: Managed Cluster Monitoring",
 "description": "Monitors hub cluster using Prometheus. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod, containers, systemd services statistics. Uses cAdvisor metrics only.",
 "tags": [ "MCM" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(container_cpu_usage_seconds_total, cluster_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network I/O pressure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network I/O pressure",
     "type": "graph",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}[5m]))",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}[5m]))",
       "legendFormat": "Sent"
      }
     ]
    }
   ]
  },
  {
   "title": "Total usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster memory usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}) / sum (machine_memory_bytes{cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster CPU usage (5m avg)",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}[5m])) / sum (machine_cpu_cores{cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}) * 100"
      }
     ]
    },
    {
     "title": "Cluster filesystem usage",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/.+$\",id=\"/\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/mapper/.+$\",id=\"/\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}) * 100"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 7 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id=\"/\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 7 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_memory_bytes{cluster_name=~\"^$cluster$\",cluster_name=~\".+\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id=\"/\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}[5m]))"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (machine_cpu_cores{cluster_name=~\"^$cluster$\",cluster_name=~\".+\"})"
      }
     ]
    },
    {
     "title": "Used",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 7 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/mapper/.+$\",id=\"/\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"})"
      }
     ]
    },
    {
     "title": "Total",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 7 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum (container_fs_limit_bytes{device=~\"^/dev/mapper/.+$\",id=\"/\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}[5m])) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name!~\"^k8s_.*\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}[5m])) by (cluster_name, name, image)",
       "legendFormat": "docker: {{ cluster_name }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{rkt_container_name!=\"\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}[5m])) by (cluster_name, rkt_container_name)",
       "legendFormat": "rkt: {{ cluster_name }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes CPU usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes CPU usage (5m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{id!=\"/\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}[5m])) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers memory usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",container_name!=\"POD\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}) by (container_name, pod_name)",
       "legendFormat": "pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{image!=\"\",name!~\"^k8s_.*\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}) by (cluster_name, name, image)",
       "legendFormat": "docker: {{ cluster_name }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (container_memory_working_set_bytes{rkt_container_name!=\"\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}) by (cluster_name, rkt_container_name)",
       "legendFormat": "rkt: {{ cluster_name }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes memory usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes memory usage",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum (container_memory_working_set_bytes{id!=\"/\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}) by (id)",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers network I/O (5m avg)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}[5m])) by (container_name, pod_name)",
       "legendFormat": "-> pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}[5m])) by (container_name, pod_name)",
       "legendFormat": "<- pod: {{ pod_name }} | {{ container_name }}"
      },
      {
       "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name!~\"^k8s_.*\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}[5m])) by (cluster_name, name, image)",
       "legendFormat": "-> docker: {{ cluster_name }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name!~\"^k8s_.*\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}[5m])) by (cluster_name, name, image)",
       "legendFormat": "<- docker: {{ cluster_name }} | {{ image }} ({{ name }})"
      },
      {
       "expr": "sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}[5m])) by (cluster_name, rkt_container_name)",
       "legendFormat": "-> rkt: {{ cluster_name }} | {{ rkt_container_name }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{rkt_container_name!=\"\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}[5m])) by (cluster_name, rkt_container_name)",
       "legendFormat": "<- rkt: {{ cluster_name }} | {{ rkt_container_name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "All processes network I/O (5m avg)",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_network_receive_bytes_total{id!=\"/\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}[5m])) by (id)",
       "legendFormat": "-> {{ id }}"
      },
      {
       "expr": "- sum (rate (container_network_transmit_bytes_total{id!=\"/\",cluster_name=~\"^$cluster$\",cluster_name=~\".+\"}[5m])) by (id)",
       "legendFormat": "<- {{ id }}"
      }
     ]
    }
   ]
  }
 ]
}