apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: multicluster-observability-addon-manager
    app.kubernetes.io/name: multicluster-observability-addon-manager
    app.kubernetes.io/part-of: multicluster-observability-addon
  name: multicluster-observability-addon-manager
  namespace: open-cluster-management-observability
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multicluster-observability-addon-manager
  template:
    metadata:
      labels:
        app: multicluster-observability-addon-manager
    spec:
      automountServiceAccountToken: false
      serviceAccountName: multicluster-observability-addon-manager
      containers:
        - name: manager
          image: quay.io/rhobs/multicluster-observability-addon:v0.0.1
          imagePullPolicy: IfNotPresent
          args:
            - "controller"
            - "--metrics-bind-address=127.0.0.1:8080"
          resources:
            requests:
              cpu: 100m
              memory: 768Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
          volumeMounts:
            - name: sa-token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
        - name: kube-rbac-proxy
          image: quay.io/stolostron/kube-rbac-proxy:latest
          imagePullPolicy: IfNotPresent
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080
            - --tls-cert-file=/etc/tls/private/tls.crt
            - --tls-private-key-file=/etc/tls/private/tls.key
            - --logtostderr=true
            - --allow-paths=/metrics
          ports:
            - name: https-metrics
              containerPort: 8443
              protocol: TCP
          resources:
            requests:
              cpu: 10m
              memory: 20Mi
            limits:
              memory: 40Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: sa-token
              mountPath: /var/run/secrets/kubernetes.io/serviceaccount
              readOnly: true
            - name: metrics-certs
              mountPath: /etc/tls/private
              readOnly: true
      volumes:
        - name: sa-token
          projected:
            sources:
              - serviceAccountToken:
                  path: token
              - configMap:
                  name: kube-root-ca.crt
                  items:
                    - key: ca.crt
                      path: ca.crt
        - name: metrics-certs
          secret:
            secretName: multicluster-observability-addon-manager-metrics-certs
