apiVersion: v1
kind: Service
metadata:
  name: multicluster-observability-addon-manager-metrics
  labels:
    app.kubernetes.io/component: multicluster-observability-addon-manager
    app.kubernetes.io/name: multicluster-observability-addon-manager
    app.kubernetes.io/part-of: multicluster-observability-addon
    app: multicluster-observability-addon-manager
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: multicluster-observability-addon-manager-metrics-certs
spec:
  type: ClusterIP
  ports:
    - name: https-metrics
      port: 8444
      targetPort: https-metrics
      protocol: TCP
  selector:
    app: multicluster-observability-addon-manager
