apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aggregate-observabilityaddons-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    owner: multicluster-observability-operator
rules:
  - verbs:
      - get
      - list
      - watch
      - create
      - delete
      - update
    apiGroups:
      - observability.open-cluster-management.io
    resources:
      - observabilityaddons
