apiVersion: apps/v1
kind: Deployment
metadata:
  name: endpoint-observability-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: endpoint-observability-operator
  template:
    metadata:
      labels:
        name: endpoint-observability-operator
    spec:
      serviceAccountName: endpoint-observability-operator-sa
      containers:
        - name: endpoint-observability-operator
          # Replace this with the built image name
          image: REPLACE_WITH_OPERATOR_IMAGE
          command:
          - endpoint-monitoring-operator
          resources:
            requests:
              cpu: 2m
              memory: 50Mi
          imagePullPolicy: Always
          ports:
          - containerPort: 8383
            name: metrics
            protocol: TCP
          env:
            - name: HUB_NAMESPACE
              value: REPLACE_WITH_HUB_CLUSTER_NAMESPACE
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: OPERATOR_NAME
              value: "endpoint-monitoring-operator"
            - name: HUB_KUBECONFIG
              value: "/spoke/hub-kubeconfig/kubeconfig"
            - name: INSTALL_PROM
              value: "false"
            - name: PULL_SECRET
              value: "REPLACE_WITH_IMAGEPULLSECRET"
          volumeMounts:
            - name: hub-kubeconfig-secret
              mountPath: "/spoke/hub-kubeconfig"
              readOnly: true
      volumes:
        - name: hub-kubeconfig-secret
          secret:
            secretName: observability-controller-hub-kubeconfig
