apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: observatorium-operator
    app.kubernetes.io/version: v0.1
    owner: multicluster-observability-operator
  name: open-cluster-management:observatorium-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:observatorium-operator
subjects:
- kind: ServiceAccount
  name: observatorium
  namespace: open-cluster-management-observability
