kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management-observability:observatorium-monitoring
  namespace: open-cluster-management-observability
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - pods
      - services
      - endpoints
