apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: open-cluster-management-observability:observatorium-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: open-cluster-management-observability:observatorium-monitoring
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring

