
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
  name: prometheus-k8s
  namespace: open-cluster-management-addon-observability
spec:
  ports:
  - name: https
    port: 9091
    targetPort: https
  selector:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
  sessionAffinity: ClientIP