apiVersion: v1
kind: Secret
metadata:
  name: prometheus-alertmanager
  namespace: open-cluster-management-addon-observability
type: Opaque
stringData:
  alertmanager.yaml: |-
    - authorization:
        type: Bearer
        credentials_file: /etc/prometheus/secrets/observability-alertmanager-accessor/token
      tls_config:
        ca_file: /etc/prometheus/secrets/obs-alertmanager-mtls-ca/ca.crt
        cert_file: /etc/prometheus/secrets/obs-alertmanager-mtls-cert/tls.crt
        key_file: /etc/prometheus/secrets/obs-alertmanager-mtls-cert/tls.key
        server_name: ""
        insecure_skip_verify: false
      follow_redirects: true
      scheme: https
      path_prefix: _PATH_PREFIX_
      timeout: 10s
      api_version: v2
      static_configs:
      - targets:
        - _ALERTMANAGER_ENDPOINT_