apiVersion: v1
kind: Secret
metadata:
  name: prometheus-alertmanager
  namespace: open-cluster-management-addon-observability
type: Opaque
stringData:
  alertmanager.yaml: |-
    - authorization:
        type: Bearer
        credentials_file: /etc/prometheus/secrets/observability-alertmanager-accessor/token
      tls_config:
        ca_file: /etc/prometheus/secrets/hub-alertmanager-router-ca/service-ca.crt
        server_name: ""
        insecure_skip_verify: false
      follow_redirects: true
      scheme: https
      path_prefix: /
      timeout: 10s
      api_version: v2
      static_configs:
      - targets:
        - _ALERTMANAGER_ENDPOINT_