{
 "title": "Metric Name Cardinality / Cluster / Namespace / Pod",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "metric_name",
    "label": "Metric name",
    "query": {
     "query": "label_values(cluster_name:cardinality,metric_name)"
    }
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(cluster_name:cardinality{metric_name=\"$metric_name\"},cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(cluster_namespace:cardinality{cluster=\"$cluster\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Metric Cardinality by Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cardinality Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(cluster_name:cardinality{metric_name=\"$metric_name\"}) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Cardinality",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(cluster_name:cardinality{metric_name=\"$metric_name\"}) by (cluster)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metric Cardinality by Namespace for Cluster $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 }
  },
  {
   "title": "Cardinality Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "topk(10, count({__name__=\"$metric_name\", cluster=\"$cluster\"}) by (namespace))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Cardinality",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "count({__name__=\"$metric_name\", cluster=\"$cluster\"}) by (namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metric Cardinality by Pod for Namespace $namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 }
  },
  {
   "title": "Cardinality Over Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "count({__name__=\"$metric_name\", cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Cardinality",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "count({__name__=\"$metric_name\", cluster=\"$cluster\", namespace=\"$namespace\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Metric Samples",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "{__name__=\"$metric_name\", cluster=\"$cluster\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}