{
 "title": "oadp-dashboard",
 "description": "Grafana Dashboard for Openshift Api Data Protecting (Velero)",
 "tags": [
  "OADP",
  "ACM",
  "Openshift"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Instance",
    "query": {
     "query": "label_values(velero_backup_attempt_total, namespace)"
    }
   },
   {
    "name": "schedule",
    "label": "Schedule",
    "query": {
     "query": "label_values(velero_backup_attempt_total, schedule)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Services & Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Velero State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=~\"$namespace\",container=\"velero\"})"
    }
   ]
  },
  {
   "title": "Restic State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg(count(kube_pod_container_status_ready{namespace=~\"$namespace\",container=\"restic\"}) by (container)) / avg(count(kube_node_role{role=\"worker\"}) by (container))*100)"
    }
   ]
  },
  {
   "title": "Registry State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(kube_pod_container_status_ready{namespace=~\"$namespace\",container=~\".*registry.*\"}) by (container)"
    }
   ]
  },
  {
   "title": "Controller Manager State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_ready{namespace=~\"$namespace\",container=\"manager\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((sum(rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\"}[5m])) by (namespace,pod,container) / on (container,pod,namespace) ((kube_pod_container_resource_limits{namespace=~\"$namespace\",resource=\"cpu\"} > 0)*300))*100)"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg((avg (container_memory_working_set_bytes{namespace=~\"$namespace\", container!=\"POD\"}) by (container,pod))/ on (container,pod)(avg (kube_pod_container_resource_limits>0 ) by (container, pod))*100)"
    }
   ]
  },
  { "title": "Backup", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Backup Existent",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_total{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Backup Executed Success",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_success_total{namespace=~\"$namespace\",schedule=~\"$schedule\"})"
    }
   ]
  },
  {
   "title": "Backup Success Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(velero_backup_success_total{namespace=~\"$namespace\",schedule=~\".*$schedule*\"}[6h])) / \nsum(rate(velero_backup_attempt_total{namespace=~\"$namespace\",schedule=~\".*$schedule*\"}[6h]))",
     "legendFormat": "Backup"
    }
   ]
  },
  {
   "title": "Backup State Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(velero_backup_success_total{namespace=~\"$namespace\",schedule=~\".*$schedule*\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(velero_backup_attempt_total{namespace=~\"$namespace\",schedule=~\".*$schedule*\"})",
     "legendFormat": "Attempts"
    },
    {
     "expr": "sum(velero_backup_deletion_success_total{namespace=~\"$namespace\",schedule=~\".*$schedule*\"})",
     "legendFormat": "Deletion Success"
    },
    {
     "expr": "sum(velero_backup_deletion_attempt_total{namespace=~\"$namespace\",schedule=~\".*$schedule*\"})",
     "legendFormat": "Deletion Attempt"
    },
    {
     "expr": "sum(velero_backup_deletion_failure_total{namespace=~\"$namespace\",schedule=~\".*$schedule\"})",
     "legendFormat": "Deletion Failure"
    },
    {
     "expr": "sum(velero_backup_failure_total{namespace=~\"$namespace\",schedule=~\".*$schedule*\"})",
     "legendFormat": "Failure"
    },
    {
     "expr": "sum(velero_backup_partial_failure_total{namespace=~\"$namespace\",schedule=~\".*$schedule*\"})",
     "legendFormat": "Partial Failure"
    }
   ]
  },
  {
   "title": "Backup Scheduler",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(velero_backup_success_total{namespace=~\"$namespace\", schedule!=\"\"})"
    }
   ]
  },
  {
   "title": "Backup Non-Scheduled",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_backup_success_total{namespace=~\"$namespace\", schedule!~\"$schedule\"})"
    }
   ]
  },
  {
   "title": "Backup Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(velero_backup_tarball_size_bytes{namespace=~\"$namespace\",schedule=~\".*$schedule*\"})",
     "legendFormat": "Total"
    },
    {
     "expr": "velero_backup_tarball_size_bytes{namespace=~\"$namespace\",schedule=~\".*$schedule*\"}",
     "legendFormat": "{{ schedule }}"
    }
   ]
  },
  {
   "title": "Backup Time Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(velero_backup_duration_seconds_bucket{namespace=~\"$namespace\",schedule=~\".*$schedule*\"}[6h])) by (schedule)",
     "legendFormat": "{{ schedule }}"
    }
   ]
  },
  { "title": "Restore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Restore Existent",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_restore_total{namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Restore Executed Success",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(velero_restore_success_total{namespace=~\"$namespace\",schedule=~\"$schedule\"}) + sum(velero_restore_success_total{namespace=~\"$namespace\",schedule!~\" \"}) "
    }
   ]
  },
  {
   "title": "Restore Success Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum( sum(rate(velero_restore_success_total{namespace=~\"$namespace\",schedule=~\"$schedule\"}[6h])) + sum(rate(velero_restore_success_total{namespace=~\"$namespace\",schedule!~\" \"}[6h])) ) \n/ \nsum( sum(rate(velero_restore_attempt_total{namespace=~\"$namespace\",schedule=~\"$schedule\"}[6h])) + sum(rate(velero_restore_attempt_total{namespace=~\"$namespace\",schedule!~\" \"}[6h])) )",
     "legendFormat": "Restore"
    }
   ]
  },
  {
   "title": "Restore State Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(velero_restore_success_total{namespace=~\"$namespace\",schedule=~\"$schedule\"}) + sum(velero_restore_success_total{namespace=~\"$namespace\",schedule!~\" \"})",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(velero_restore_attempt_total{namespace=~\"$namespace\",schedule=~\"$schedule\"}) + sum(velero_restore_attempt_total{namespace=~\"$namespace\",schedule!~\" \"})",
     "legendFormat": "Attempts"
    },
    {
     "expr": "sum(velero_restore_failed_total{namespace=~\"$namespace\",schedule=~\"$schedule\"}) + sum(velero_restore_failed_total{namespace=~\"$namespace\",schedule!~\" \"})",
     "legendFormat": "Failure"
    },
    {
     "expr": "sum(velero_restore_partial_failure_total{namespace=~\"$namespace\",schedule=~\"$schedule\"}) + sum(velero_restore_partial_failure_total{namespace=~\"$namespace\",schedule!~\" \"})",
     "legendFormat": "Partial Failure"
    },
    {
     "expr": "sum(velero_restore_validation_failed_total{namespace=~\"$namespace\",schedule=~\"$schedule\"}) + sum(velero_restore_validation_failed_total{namespace=~\"$namespace\",schedule!~\" \"})",
     "legendFormat": "Validation Failure"
    }
   ]
  },
  { "title": "Snapshot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Snapshot State Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(velero_volume_snapshot_success_total{namespace=~\"$namespace\",schedule=~\"$schedule\"})",
     "legendFormat": "Success"
    },
    {
     "expr": "sum(velero_volume_snapshot_attempt_total{namespace=~\"$namespace\",schedule=~\"$schedule\"})",
     "legendFormat": "Attempts"
    },
    {
     "expr": "sum(velero_volume_snapshot_failure_total{namespace=~\"$namespace\",schedule=~\"$schedule\"})",
     "legendFormat": "Failed"
    }
   ]
  }
 ]
}