apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: multicluster-observability-operator
  creationTimestamp: null
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      namespace: $(SERVICE_NAMESPACE)
      name: $(SERVICE)
      path: /validate
  failurePolicy: Fail
  name: vmulticlusterobservability.observability.open-cluster-management.io
  rules:
  - apiGroups:
    - observability.open-cluster-management.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - multiclusterobservabilities
  sideEffects: None



        service:
          namespace: $(SERVICE_NAMESPACE)
          name: $(SERVICE)
          port: 443
          path: /convert
        caBundle: XG4=