apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: multicluster-observability-operator
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"

