apiVersion: v1
data:
  config.yaml: |
    alertmanagers:
    - scheme: https
      path_prefix: /api/alertmanager/v2
      http_config:
        tls_config:
          ca_file: /etc/thanos/secrets/server-ca-certs/ca.crt
      static_configs:
      - observability-observatorium-api.open-cluster-management-observability.svc.cluster.local:8080
      api_version: v2
kind: ConfigMap
metadata:
  name: thanos-ruler-config
  namespace: open-cluster-management
