apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:thanos-rule
  labels:
    owner: multicluster-observability-operator
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
