{
 "title": "Kubernetes / Service-Level Overview / API Server",
 "tags": [
  "kubernetes-mixin",
  "SLO"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(sli:apiserver_request_duration_seconds:trend:1m, cluster)"
    }
   },
   { "name": "window", "label": "Window", "query": "7d,30d" },
   { "name": "top", "label": "Top", "query": "5, 10, 20, 50, 100" }
  ]
 },
 "panels": [
  {
   "title": "Fleet Overview ($cluster) - $window",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "# of cluster that has exceeded the SLO",
   "type": "stat",
   "description": "A total number of the clusters that have exceeded their SLO target.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(sum_over_time(sli:apiserver_request_duration_seconds:bin:trend:1m{cluster=~\"$cluster\"}[$__range])) / count_over_time(sli:apiserver_request_duration_seconds:bin:trend:1m{cluster=~\"$cluster\"}[$__range]) < bool 0.99)"
    }
   ]
  },
  {
   "title": "# of clusters that are meeting the SLO",
   "type": "stat",
   "description": "A total number of clusters that haven't breached the SLO target.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(floor(sum_over_time(sli:apiserver_request_duration_seconds:bin:trend:1m{cluster=~\"$cluster\"}[$__range])) / count_over_time(sli:apiserver_request_duration_seconds:bin:trend:1m{cluster=~\"$cluster\"}[$__range]) >= bool 0.99))"
    }
   ]
  },
  {
   "title": "Topk Clusters ($top)",
   "type": "table",
   "description": "List of the topk cluster over a $window period. The results are sorted from worst offending clusters to passing clusters.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sort_desc(bottomk($top, floor(sum_over_time(sli:apiserver_request_duration_seconds:bin:trend:1m{cluster=~\"$cluster\"}[$__range])) / count_over_time(sli:apiserver_request_duration_seconds:bin:trend:1m{cluster=~\"$cluster\"}[$__range])))"
    }
   ]
  },
  {
   "title": "API Server Request Duration - Status ($cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }
  },
  {
   "title": "Topk Cluster's SLI Trend ($top)",
   "type": "graph",
   "description": "The service level indicator (SLI) trend of the topk clusters over a relative time. The results are sorted from worst offending clusters to passing clusters.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "bottomk($top, sli:apiserver_request_duration_seconds:trend:1m{cluster=~\"$cluster\"})"
    },
    { "expr": "0.9900" }
   ]
  }
 ]
}