apiVersion: v1
data:
  acm-openshift-virtual-machines-inventory.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "description": "This dashboard provides a comprehensive list of all virtual machines across clusters, offering detailed insights into each configuration of the virtual machines. You can easily search and filter virtual machines based on various attributes, enabling quick access to specific information for effective management and troubleshooting.",
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 39,
      "iteration": 1727182897906,
      "links": [],
      "panels": [
        {
          "datasource": null,
          "description": "",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "thresholds"
              },
              "custom": {
                "align": "auto",
                "displayMode": "auto"
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  },
                  {
                    "color": "red",
                    "value": 80
                  }
                ]
              }
            },
            "overrides": [
              {
                "matcher": {
                  "id": "byType",
                  "options": "string"
                },
                "properties": [
                  {
                    "id": "custom.filterable",
                    "value": true
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "Value #E"
                },
                "properties": [
                  {
                    "id": "unit",
                    "value": "decbytes"
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byName",
                  "options": "Guest Agent"
                },
                "properties": [
                  {
                    "id": "mappings",
                    "value": [
                      {
                        "options": {
                          "1": {
                            "index": 1,
                            "text": "Reporting"
                          }
                        },
                        "type": "value"
                      },
                      {
                        "options": {
                          "match": "null",
                          "result": {
                            "index": 0,
                            "text": "Not Reporting"
                          }
                        },
                        "type": "special"
                      }
                    ]
                  }
                ]
              },
              {
                "matcher": {
                  "id": "byType",
                  "options": "number"
                },
                "properties": [
                  {
                    "id": "custom.filterable",
                    "value": true
                  }
                ]
              }
            ]
          },
          "gridPos": {
            "h": 26,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 2,
          "options": {
            "showHeader": true,
            "sortBy": [
              {
                "desc": false,
                "displayName": "Allocated memory"
              }
            ]
          },
          "pluginVersion": "8.5.20",
          "targets": [
            {
              "exemplar": true,
              "expr": "sum by (cluster, namespace, name, status) (\n  label_replace(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"} > 0, \"status\", \"running\", \"__name__\", \".*\") \n  or label_replace(kubevirt_vm_non_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"} > 0, \"status\", \"stopped\", \"__name__\", \".*\")\n  or label_replace(kubevirt_vm_error_status_last_transition_timestamp_seconds{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"} > 0, \"status\", \"error\", \"__name__\", \".*\") \n  or label_replace(kubevirt_vm_starting_status_last_transition_timestamp_seconds{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"} > 0, \"status\", \"starting\", \"__name__\", \".*\") \n  or label_replace(kubevirt_vm_migrating_status_last_transition_timestamp_seconds{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"} > 0, \"status\", \"migrating\", \"__name__\", \".*\")\n)",
              "format": "table",
              "hide": false,
              "instant": true,
              "interval": "",
              "legendFormat": "",
              "refId": "A"
            },
            {
              "exemplar": true,
              "expr": "kubevirt_vmi_info{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"}",
              "format": "table",
              "hide": false,
              "instant": true,
              "interval": "",
              "legendFormat": "",
              "refId": "B"
            },
            {
              "exemplar": true,
              "expr": "sum by (cluster, namespace, name, node)(kubevirt_vmi_network_receive_bytes_total{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\"})",
              "format": "table",
              "hide": false,
              "instant": true,
              "interval": "",
              "legendFormat": "",
              "refId": "C"
            },
            {
              "exemplar": true,
              "expr": "sum by (cluster, namespace, name) (\n  (\n    last_over_time(kubevirt_vm_resource_requests{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", resource=\"cpu\", unit=\"cores\"}[1h])\n  ) \n  * (\n    last_over_time(kubevirt_vm_resource_requests{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", resource=\"cpu\", unit=\"sockets\"}[1h])\n  ) \n  * (\n    last_over_time(kubevirt_vm_resource_requests{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", resource=\"cpu\", unit=\"threads\"}[1h])\n  )\n)",
              "format": "table",
              "hide": false,
              "instant": true,
              "interval": "",
              "legendFormat": "",
              "refId": "D"
            },
            {
              "exemplar": true,
              "expr": "sum by (cluster, namespace, name)(kubevirt_vm_resource_requests{cluster=~\"$cluster\", name=~\"$name\", namespace=~\"$namespace\", resource=\"memory\"})",
              "format": "table",
              "hide": false,
              "instant": true,
              "interval": "",
              "legendFormat": "",
              "refId": "E"
            },
            {
              "exemplar": true,
              "expr": "sum by (cluster, namespace, name)(kubevirt_vmi_memory_available_bytes{cluster=~\"$cluster\", namespace=~\"$namespace\", name=~\"$name\"}*0+1)",
              "format": "table",
              "hide": false,
              "instant": true,
              "interval": "",
              "legendFormat": "",
              "refId": "F"
            }
          ],
          "title": "Virtual Machines Inventory",
          "transformations": [
            {
              "id": "merge",
              "options": {}
            },
            {
              "id": "organize",
              "options": {
                "excludeByName": {
                  "Time": true,
                  "Value #A": true,
                  "Value #B": true,
                  "Value #C": true,
                  "__name__": true,
                  "clusterID": true,
                  "container": true,
                  "endpoint": true,
                  "guest_os_kernel_release": true,
                  "guest_os_machine": true,
                  "instance": true,
                  "job": true,
                  "os": true,
                  "phase": true,
                  "pod": true,
                  "receive": true,
                  "service": true,
                  "tenant_id": true
                },
                "indexByName": {
                  "Time": 0,
                  "Value #A": 17,
                  "Value #B": 32,
                  "Value #C": 33,
                  "Value #D": 6,
                  "Value #E": 7,
                  "Value #F": 8,
                  "Value #G": 9,
                  "__name__": 18,
                  "cluster": 1,
                  "clusterID": 19,
                  "container": 20,
                  "endpoint": 21,
                  "evictable": 22,
                  "flavor": 16,
                  "guest_os_kernel_release": 23,
                  "guest_os_machine": 24,
                  "guest_os_name": 10,
                  "guest_os_version_id": 11,
                  "instance": 25,
                  "instance_type": 12,
                  "job": 26,
                  "name": 3,
                  "namespace": 2,
                  "node": 5,
                  "os": 27,
                  "phase": 13,
                  "pod": 28,
                  "preference": 14,
                  "receive": 29,
                  "service": 30,
                  "status": 4,
                  "tenant_id": 31,
                  "workload": 15
                },
                "renameByName": {
                  "Value #A": "",
                  "Value #D": "Total Allocated vCPUs",
                  "Value #E": "Allocated memory",
                  "Value #F": "Guest Agent",
                  "Value #G": "",
                  "cluster": "Cluster",
                  "flavor": "Flavor",
                  "guest_os_name": "OS Name",
                  "guest_os_version_id": "OS Version",
                  "instance_type": "Instance Type",
                  "name": "VM Name",
                  "namespace": "Namespace",
                  "node": "Node",
                  "os": "",
                  "phase": "Phase",
                  "preference": "Preference",
                  "status": "Status",
                  "vmi": "VM Name",
                  "workload": "Workload"
                }
              }
            }
          ],
          "type": "table"
        }
      ],
      "refresh": "",
      "schemaVersion": 30,
      "style": "dark",
      "tags": [
        "Virtualization",
        "OpenShift",
        "ACM",
        "KubeVirt"
      ],
      "templating": {
        "list": [
          {
            "allValue": "",
            "datasource": null,
            "definition": "label_values(kubevirt_vm_running_status_last_transition_timestamp_seconds, cluster)",
            "description": null,
            "error": null,
            "hide": 0,
            "includeAll": false,
            "label": "Cluster",
            "multi": false,
            "name": "cluster",
            "options": [],
            "query": {
              "query": "label_values(kubevirt_vm_running_status_last_transition_timestamp_seconds, cluster)",
              "refId": "StandardVariableQuery"
            },
            "refresh": 2,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          },
          {
            "allValue": ".*",
            "current": {
              "selected": true,
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": null,
            "definition": "label_values(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}, namespace)",
            "description": "Filter the virtual machine by the namespace.",
            "error": null,
            "hide": 0,
            "includeAll": true,
            "label": "Namespace",
            "multi": true,
            "name": "namespace",
            "options": [],
            "query": {
              "query": "label_values(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\"}, namespace)",
              "refId": "StandardVariableQuery"
            },
            "refresh": 2,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          },
          {
            "allValue": ".*",
            "current": {
              "selected": true,
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": null,
            "definition": "label_values(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\"}, name)",
            "description": "Filter the virtual machine by the name.",
            "error": null,
            "hide": 0,
            "includeAll": true,
            "label": "VM Name",
            "multi": true,
            "name": "name",
            "options": [],
            "query": {
              "query": "label_values(kubevirt_vm_running_status_last_transition_timestamp_seconds{cluster=~\"$cluster\", namespace=~\"$namespace\"}, name)",
              "refId": "StandardVariableQuery"
            },
            "refresh": 2,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          }
        ]
      },
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Inventory dashboards / Virtual Machines Inventory",
      "uid": "Q2U8w8qIz",
      "version": 1
    }
kind: ConfigMap
metadata:
  name: grafana-dashboard-acm-virtual-machines-inventory
  namespace: open-cluster-management-observability
  annotations:
    observability.open-cluster-management.io/dashboard-folder: "ACM / OpenShift Virtualization"
