apiVersion: v1
data:
  acm-cluster-by-alerts.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "target": {
              "limit": 100,
              "matchAny": false,
              "tags": [],
              "type": "dashboard"
            },
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 39,
      "iteration": 1682102035672,
      "links": [
        {
          "asDropdown": false,
          "icon": "dashboard",
          "includeVars": false,
          "keepTime": false,
          "tags": [],
          "targetBlank": true,
          "title": "Alert Analysis",
          "tooltip": "",
          "type": "link",
          "url": "d/w1V3PRTnk/alert-analysis?orgId=1"
        },
        {
          "asDropdown": false,
          "icon": "dashboard",
          "includeVars": false,
          "keepTime": false,
          "tags": [],
          "targetBlank": true,
          "title": "Alerts by Cluster",
          "tooltip": "",
          "type": "link",
          "url": "d/7GMQIsJnz/alerts-by-cluster?orgId=1"
        }
      ],
      "panels": [
        {
          "collapsed": false,
          "datasource": null,
          "gridPos": {
            "h": 1,
            "w": 24,
            "x": 0,
            "y": 0
          },
          "id": 4,
          "panels": [],
          "title": "Real Time Data",
          "type": "row"
        },
        {
          "datasource": null,
          "description": "Alert: $alert - $description",
          "fieldConfig": {
            "defaults": {
              "color": {
                "mode": "palette-classic"
              },
              "custom": {
                "axisLabel": "",
                "axisPlacement": "auto",
                "barAlignment": 0,
                "drawStyle": "bars",
                "fillOpacity": 70,
                "gradientMode": "none",
                "hideFrom": {
                  "legend": false,
                  "tooltip": false,
                  "viz": false
                },
                "lineInterpolation": "linear",
                "lineWidth": 2,
                "pointSize": 5,
                "scaleDistribution": {
                  "type": "linear"
                },
                "showPoints": "auto",
                "spanNulls": false,
                "stacking": {
                  "group": "A",
                  "mode": "normal"
                },
                "thresholdsStyle": {
                  "mode": "off"
                }
              },
              "mappings": [],
              "thresholds": {
                "mode": "absolute",
                "steps": [
                  {
                    "color": "green",
                    "value": null
                  }
                ]
              }
            },
            "overrides": []
          },
          "gridPos": {
            "h": 11,
            "w": 24,
            "x": 0,
            "y": 1
          },
          "id": 2,
          "options": {
            "legend": {
              "calcs": [],
              "displayMode": "list",
              "placement": "bottom"
            },
            "tooltip": {
              "mode": "single"
            }
          },
          "pluginVersion": "8.1.3",
          "targets": [
            {
              "exemplar": true,
              "expr": "sum(ALERTS{alertstate=\"firing\", alertname=~\"$alert\", severity=~\"$severity\"}) by (cluster)",
              "hide": false,
              "instant": false,
              "interval": "",
              "legendFormat": "{{ cluster }}",
              "refId": "A"
            }
          ],
          "title": "Clusters with Alert - Severity ($severity)",
          "type": "timeseries"
        }
      ],
      "refresh": "",
      "schemaVersion": 30,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": [
          {
            "allValue": null,
            "current": {
              "selected": true,
              "text": [
                "All"
              ],
              "value": [
                "$__all"
              ]
            },
            "datasource": null,
            "definition": "label_values(ALERTS, alertname)",
            "description": null,
            "error": null,
            "hide": 0,
            "includeAll": true,
            "label": "Alert",
            "multi": true,
            "name": "alert",
            "options": [],
            "query": {
              "query": "label_values(ALERTS, alertname)",
              "refId": "StandardVariableQuery"
            },
            "refresh": 2,
            "regex": "",
            "skipUrlSync": false,
            "sort": 5,
            "type": "query"
          },
          {
            "allValue": null,
            "current": {
              "selected": false,
              "text": "All",
              "value": "$__all"
            },
            "datasource": null,
            "definition": "label_values(ALERTS{alertname=~\"$alert\"}, severity)",
            "description": null,
            "error": null,
            "hide": 0,
            "includeAll": true,
            "label": "Severity",
            "multi": false,
            "name": "severity",
            "options": [],
            "query": {
              "query": "label_values(ALERTS{alertname=~\"$alert\"}, severity)",
              "refId": "StandardVariableQuery"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "type": "query"
          }
        ]
      },
      "time": {
        "from": "now-30m",
        "to": "now"
      },
      "timepicker": {
        "refresh_intervals": [
          "5s",
          "10s",
          "30s",
          "1m",
          "5m",
          "15m",
          "30m",
          "1h",
          "2h",
          "1d"
        ]
      },
      "timezone": "",
      "title": "Clusters by Alert",
      "uid": "UZJv0TJnz",
      "version": 1
    }
kind: ConfigMap
metadata:
  name: grafana-dashboard-acm-cluster-by-alerts
  namespace: open-cluster-management-observability
  annotations:
    observability.open-cluster-management.io/dashboard-folder: "Alerts"
