{
 "title": "Alert Analysis",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "severity", "query": { "query": "label_values(ALERTS, severity)" } }
  ]
 },
 "panels": [
  { "title": "Real Time Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Alerts",
   "type": "stat",
   "description": "Total number of alerts that are firing.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Critical Alerts",
   "type": "stat",
   "description": "Total number of alerts that are firing with the severity level: critical.",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",severity=\"critical\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Warning Alerts",
   "type": "stat",
   "description": "Total number of alerts that are firing with the severity level: warning.",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",severity=\"warning\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Moderate Alerts",
   "type": "stat",
   "description": "Total number of alerts that are firing with the severity level: moderate.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",severity=\"moderate\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Low Alerts",
   "type": "stat",
   "description": "Total number of alerts that are firing with the severity level: low.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",severity=\"low\"}) or vector(0)"
    }
   ]
  },
  {
   "title": "AlertType Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\",severity=~\"$severity\"}) by (alertname)",
     "legendFormat": "{{ alertname }}"
    }
   ]
  },
  {
   "title": "Cluster Affected Over Time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\", cluster!=\"\", severity=~\"$severity\"}) by (cluster)",
     "legendFormat": "{{ cluster }}"
    }
   ]
  },
  {
   "title": "Alerts and Clusters",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "sum(ALERTS{alertstate=\"firing\"}) by (cluster,alertname,severity)"
    }
   ]
  },
  {
   "title": "Historical Analysis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Most Firing Alerts",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(ALERTS{alertstate=\"firing\",severity=~\"$severity\"}[$__range])) by (alertname)",
       "legendFormat": "{{alertname}}"
      }
     ]
    },
    {
     "title": "Most Affected Clusters",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(ALERTS{alertstate=\"firing\", cluster!=\"\",severity=~\"$severity\"}[$__range])) by (cluster)",
       "legendFormat": "{{cluster}}"
      }
     ]
    }
   ]
  }
 ]
}