{
 "title": "Kubernetes / Service Level Overview / Cluster",
 "tags": [
  "kubernetes-mixin",
  "SLO"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(sli:apiserver_request_duration_seconds:bin:trend:5m,cluster)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Critical Alerts",
   "type": "stat",
   "description": "A total number of critical alerts firing within the cluster: $cluster.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Non-Critical Alerts",
   "type": "stat",
   "description": "A total number of non-critical alerts firing within the cluster: $cluster.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sli:apiserver_request_duration_seconds:trend:5m{cluster=~\"$cluster\", slo=\"$slo\"}"
    }
   ]
  },
  {
   "title": "OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "OK",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "API Server - Request Duration - Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Target",
   "type": "stat",
   "description": "The service level target for the API server request duration SLO.",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sli:apiserver_request_duration_seconds:bin:trend:5m"
    }
   ]
  },
  {
   "title": "Past 7 Days",
   "type": "stat",
   "description": "SLO status from over a 7 days period. (The SLO is calculated from # of request duration >= target / total count of request durations)",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum_over_time(sli:apiserver_request_duration_seconds:bin:trend:5m{cluster=\"$cluster\"}[$__range])) / count_over_time(sli:apiserver_request_duration_seconds:bin:trend:5m{cluster=\"$cluster\"}[$__range])"
    }
   ]
  },
  {
   "title": "Past 30 Days",
   "type": "stat",
   "description": "SLO status from over a 30 days period. (The SLO is calculated from # of request duration >= target / total count of request durations)",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum_over_time(sli:apiserver_request_duration_seconds:bin:trend:5m{cluster=\"$cluster\"}[$__range])) / count_over_time(sli:apiserver_request_duration_seconds:bin:trend:5m{cluster=\"$cluster\"}[$__range])"
    }
   ]
  },
  { "title": "Burn Rates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "2% Budget Consumed - Over 7 Day Window (1h)",
   "type": "stat",
   "description": "The burn rate measure of how fast the service consumes 2% of the error budget within a 1-hour alerting window over a 7-day period.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sli:apiserver_request_duration_seconds:bin:trend:5m{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "5% Budget Consumed - Over 7 Day Window (6h)",
   "type": "stat",
   "description": "The burn rate measure of how fast the service consumes 2% of the error budget within a 6-hour alerting window over a 7-day period.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum_over_time(sli:apiserver_request_duration_seconds:bin:trend:5m{cluster=\"$cluster\"}[$__range])) / count_over_time(sli:apiserver_request_duration_seconds:bin:trend:5m{cluster=\"$cluster\"}[$__range])"
    }
   ]
  },
  {
   "title": "2% Budget Consumed - Over 30 Day Window (1h)",
   "type": "stat",
   "description": "The burn rate measure of how fast the service consumes 2% of the error budget within a 1-hour alerting window over a 30-day period.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum_over_time(sli:apiserver_request_duration_seconds:bin:trend:5m{cluster=\"$cluster\"}[$__range])) / count_over_time(sli:apiserver_request_duration_seconds:bin:trend:5m{cluster=\"$cluster\"}[$__range])"
    }
   ]
  },
  {
   "title": "5% Budget Consumed - Over 30 Day Window (6h)",
   "type": "stat",
   "description": "The burn rate measure of how fast the service consumes 5% of the error budget within a 6-hour alerting window over a 30-day period.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum_over_time(sli:apiserver_request_duration_seconds:bin:trend:5m{cluster=\"$cluster\"}[$__range])) / count_over_time(sli:apiserver_request_duration_seconds:bin:trend:5m{cluster=\"$cluster\"}[$__range])"
    }
   ]
  },
  { "title": "Trend / Error Budget", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "API Server - Request Duration - SLI",
   "type": "graph",
   "description": "Trending graph of the service level indicators (SLI) over relative time period used to compute the service level objective (SLO).",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sli:apiserver_request_duration_seconds:trend:5m{cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "API Server - Request Duration - Error Budget",
   "type": "gauge",
   "description": "The error budget for the API server request duration SLO.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum_over_time(sli:apiserver_request_duration_seconds:bin:trend:5m{cluster=\"$cluster\"}[$__range])) / count_over_time(sli:apiserver_request_duration_seconds:bin:trend:5m{cluster=\"$cluster\"}[$__range])"
    }
   ]
  }
 ]
}