apiVersion: v1
kind: Service
metadata:
  labels:
    app: multicluster-observability-grafana
  name: grafana
  namespace: open-cluster-management-observability
  annotations:
    service.alpha.openshift.io/serving-cert-secret-name: grafana-tls
spec:
  ports:
  - name: oauth-proxy
    port: 9443
    protocol: TCP
    targetPort: 9443
  selector:
    app: multicluster-observability-grafana
  type: ClusterIP
