{
 "title": "Policy Overview",
 "tags": [ "ACM" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Policy NonCompliant %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(cluster:policy_governance_info:propagated_noncompliant_count/cluster:policy_governance_info:propagated_count) * 100",
     "legendFormat": "{{ cluster_namespace }}"
    }
   ]
  },
  {
   "title": "Violations per Policy",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "policy:policy_governance_info:propagated_noncompliant_count{}\n",
     "legendFormat": "{{ policy }}"
    }
   ]
  },
  {
   "title": "Failed Policy by category",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(policyreport_info{result=\"fail\"}) by (category)",
     "legendFormat": "{{ category }}"
    }
   ]
  },
  {
   "title": "Failed Policy by severity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(policyreport_info{result=\"fail\"}) by (severity)\r",
     "legendFormat": "{{ severity }}"
    }
   ]
  }
 ]
}