apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: setup-grafana-dev
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - services
  - services/finalizers
  - persistentvolumeclaims
  - secrets
  verbs:
  - get
  - create
  - list
  - delete
  - update
  - patch
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
  - delete
  - update
  - list
  - patch
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
- apiGroups:
  - integreatly.org
  resources:
  - grafanas
  - grafanas/status
  - grafanas/finalizers
  - grafanadashboards
  - grafanadashboards/status
  - grafanadatasources
  - grafanadatasources/status
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - deletecollection
  - watch
- apiGroups:
  - apps
  resourceNames:
  - multicluster-observability-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
  - watch
- apiGroups:
  - observability.open-cluster-management.io
  resources:
  - '*'
  - multiclusterobservabilities
  - endpointmonitorings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
