apiVersion: v1
kind: Secret
metadata:
  name: thanos-object-storage
  namespace: open-cluster-management-observability
type: Opaque
stringData:
  thanos.yaml: |
    type: s3
    config:
      bucket: acm-observability-thanostore
      endpoint: minio:9000
      insecure: true
      access_key: minioadmin
      secret_key: minioadmin
