{
 "title": "ACM - Resources - Hosted Control Plane",
 "tags": [ "ACM" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "hcp_ns",
    "label": "HCP Namespace",
    "query": {
     "query": "label_values(mce_hs_addon_hosted_control_planes_status_gauge, hcp_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_info{namespace=\"$hcp_ns\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 16, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"$hcp_ns\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Requests %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum{namespace=\"$hcp_ns\"}) by (namespace) / sum(kube_pod_container_resource_requests{resource=\"cpu\",namespace=\"$hcp_ns\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "CPU Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$hcp_ns\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum{namespace=\"$hcp_ns\"}"
    }
   ]
  },
  {
   "title": "Memory Requests %",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=\"$hcp_ns\", container!=\"\"}) by (namespace) / sum(kube_pod_container_resource_requests{namespace=\"$hcp_ns\", resource=\"memory\"}) by (namespace)"
    }
   ]
  },
  {
   "title": "Memory Usage (w/o cache)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 21, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{job=\"kubelet\",namespace=~\"$hcp_ns\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests{namespace=\"$hcp_ns\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{namespace=\"$hcp_ns\", container!=\"\"})"
    }
   ]
  }
 ]
}