---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: thanos-compact
  namespace: open-cluster-management-observability
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: thanos-compact
  ingress:
    - ports:
        - port: 10902
          protocol: TCP
  egress:
    - {}
  policyTypes:
    - Ingress
    - Egress
