name: Mark stale issues and pull requests
on:
  schedule:
    - cron: '0 12 * * Mon-Fri' # Github Actions job run in UTC. Running at 12PM UTC, will schedule the job for 8AM EST.

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v3
        with:
          close-pr-label: 'no-pr-activity'
          close-pr-message: 'Closing pull-request due to lack of activity.'
          days-before-close: 7
          days-before-stale: 5
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-pr-label: 'stale'
          stale-pr-message: "This pr has been automatically marked as stale because it has not had recent activity. It will be closed in 7 days (1 week), if no further activity occurs."
